### ISSUE TITLE
Fix status bar transparent

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#100]
## Kind (Required)
- Improvement

 ## Overview (Required)

-  Currently
![image](https://user-images.githubusercontent.com/1386930/109375076-42572b00-78fd-11eb-8dc8-0d947c280a3e.png)

- DroidKaigi 2020
![image](https://user-images.githubusercontent.com/1386930/109375091-56029180-78fd-11eb-89e9-109c76d89acf.png)

 ## Links	

-

**Comment by a25max** [comment]
I want to try it. 🙋‍♂️

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
