### ISSUE TITLE
Show DroidKaigi logo instead of Toolbar text

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#101]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/109375239-b219e580-78fe-11eb-97c7-41500fbf6247.png)
![image](https://user-images.githubusercontent.com/1386930/109375254-c6f67900-78fe-11eb-835d-02f5f2b4e436.png)

 ## Links	

- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=0%3A1

**Comment by kwQt** [comment]
I'll try this issue :raising_hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
