### ISSUE TITLE
Fix divider

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#102]
## Kind (Required)

- Improvement

 ## Overview (Required)

current
- 
![image](https://user-images.githubusercontent.com/1386930/109375406-dcb86e00-78ff-11eb-8cb7-fb8ea8df1f5d.png)

design
- 
![image](https://user-images.githubusercontent.com/1386930/109375413-e80b9980-78ff-11eb-9674-beb6d5445ec7.png)

 ## Links	

- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=0%3A1

**Comment by ttanaka330** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
