### ISSUE TITLE
Use painterResource() instead of ImageBitmap.imageResource() and ImageVector.vectorResource()

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#103]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Probably, the painter seems to be better because you don't have to be aware of either vector or bitmap.

 ## Links	

-

**Comment by Pluu** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks as always! Assigned!
