### ISSUE TITLE
Fix package staff instead of core for staff screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#104]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  the title says everything
- Please move it and change package

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/tree/01b8b31305199243344357375ddd3469bf314340/uicomponent-compose/other/src/main/java/io/github/droidkaigi/feeder/core

**Comment by mightyfrog** [comment]
I'll take care of this.

**Comment by takahirom** [comment]
Thanks! Assigned!
