### ISSUE TITLE
Show placeholder android robot for placeholder

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#105]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/109375731-5c473c80-7902-11eb-87d8-ff1cf57b951c.png)

 ## Links	

-

**Comment by mightyfrog** [comment]
I'll take care of it.

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
