### ISSUE TITLE
Add open source license screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#106]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This screen is placed in the following location.
- https://github.com/DroidKaigi/conference-app-2021/issues/260
- You don't need to put a link on the about screen for this development.

 ## Links	

-

**Comment by yoshida0261** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
