### ISSUE TITLE
Add Japanese translation for error messages

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#107]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please add Japanese resource for errors

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/1ee1164b9bcdf6bc0cdedbe2933fa6d4e2913436/uicomponent-compose/core/src/main/res/values/strings.xml#L3

**Comment by ked4ma** [comment]
:raising_hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
