### ISSUE TITLE
Implement ProgressTimeLatch for Compose

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#108]
## Kind (Required)

- Improvement

 ## Overview (Required)

- ProgressTimeLatch prevents the progress bar from flickering. Please search for more information. 

 ## Links	

-

**Comment by sobaya-0141** [comment]
:raising_hand:

**Comment by KeithYokoma** [comment]
@sobaya-0141 Thanks and go for it! 👍
