### ISSUE TITLE
Use Action model pattern for navigation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#111]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This is the implementation pattern in compose-sample.

 ## Links	

- https://github.com/android/compose-samples/blob/2cff65334ea023956a58f215a13b6a55c7e1e18f/Owl/app/src/main/java/com/example/owl/ui/NavGraph.kt#L75

**Comment by ked4ma** [comment]
I try tackle to this issue!

**Comment by takahirom** [comment]
Thank you for your tackling 🔥
