### ISSUE TITLE
Add "Kaigi" to IDE dictionary

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#114]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/109376558-a03d4000-7908-11eb-99f5-031fb0336474.png)

 ## Links	

-

**Comment by ue-moo** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 📚
