### ISSUE TITLE
Show speaker icon for droidkaigi fm

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#115]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We can use icons!  ![image](https://user-images.githubusercontent.com/1386930/109376607-0e820280-7909-11eb-932c-002186e46faa.png)
 - design
![image](https://user-images.githubusercontent.com/1386930/109376619-2c4f6780-7909-11eb-9bcd-a02ab682cfec.png)

 ## Links	

- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=0%3A1

**Comment by KoutaMatsushita** [comment]
I want to try it. 🙋‍♂️

**Comment by mhidaka** [comment]
Assigned! Thank you!
