### ISSUE TITLE
Delete duplicate code

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#117]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I have specified the width twice, but it should be enough once.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/01b8b31305199243344357375ddd3469bf314340/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt#L79-L80

**Comment by nanaten** [comment]
🙋‍♀️

**Comment by takahirom** [comment]
Thanks! I think this is the easiest issue 😄
