### ISSUE TITLE
Bundle DroidKaigi FM in app

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#118]
## Kind (Required)

- Improvement

 ## Overview (Required)
 - Can we play it in the app?
 - The mp3 url seems to have regularity and may be usable.
 - https://droidkaigi.jp/fm/audio/droidkaigi-fm_6.mp3

 ## Links	

-

**Comment by akihiro-n** [comment]
I'm interested in this task and would like to see more information.

1. Use the link value included in FeedItem.Podcast to generate an mp3 URL based on regularity.
For example ``` link = "https://droidkaigi.jp/fm/episode/5"``` → ```https://droidkaigi.jp/fm/audio/droidkaigi-fm_5.mp3```
1. Play mp3 on app.  For example, when you tap the thumbnail image?

Is my perception correct?

**Comment by takahirom** [comment]
Yes, your perception is collect. 👍 
Perhaps it's better to show if it's playing now. ⏯️

**Comment by akihiro-n** [comment]
Thank you👍 
 I will try this issue😺

**Comment by takahirom** [comment]
Thanks! Assigned 👍 I'm looking forward to your job!
