### ISSUE TITLE
Set a projcet icon for our Android Studio project

### ISSUE THREAD

**Issue by mhidaka** [DroidKaigi/conference-app-2021#119]
## Kind (Required)

- Other

 ## Overview (Required)

-  we are looking for a contributor to set a project icon on an Android Studio project to make it easier for better visibility.

 ## Links	

- [How to set a project icon](https://qiita.com/ryo_mm2d/items/ad60dfc8491bb57f3522)
- [Visual Identity](https://github.com/DroidKaigi/visual-identity/)
  - [DroidKaigi Icon](https://github.com/DroidKaigi/visual-identity/blob/master/Logo/png/Symbol.png)

<img width="436" alt="Symbol" src="https://user-images.githubusercontent.com/322019/109377129-a2090280-790c-11eb-9f1d-49b5daa23a38.png">

**Comment by kkt-yu** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 🎨
