### ISSUE TITLE
Define shape theming

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#120]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Right now it is defined for each widget, but it should be possible to set it with theme. 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/610ad01d00a673211e9bcef716762c367cdb53d6/uicomponent-compose/core/src/main/java/io/github/droidkaigi/feeder/core/theme/Shape.kt#L8

**Comment by NUmeroAndDev** [comment]
🙋

**Comment by takahirom** [comment]
Thanks!Assigned🙏
You are first contributor!!🥇
