### ISSUE TITLE
Use MultiLangText model for title and summary

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#121]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Now FeedItem has a value as a string, but I want to use MultiLangText because it can contain content in multiple languages.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/f6d311de4fb522d412f5786022474305b7048ac0/data/api/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/KtorFeedApi.kt#L47-L50

**Comment by blackbracken** [comment]
I will try this issue. @takahirom

**Comment by takahirom** [comment]
Thanks! Assigned 👍 If you have any questions, please tell me!

**Comment by blackbracken** [comment]
Some texts are either Japanese or English language only, so would it be okay if I translate it?

**Comment by takahirom** [comment]
Since the API is also under development, please develop without worrying about the contents of the API. 👍 
The PR developer for this issue does not need to translate the wording. 😄
