### ISSUE TITLE
Delete unneeded namespace

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#124]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  
![image](https://user-images.githubusercontent.com/1386930/109382579-9a555800-7924-11eb-8cf2-a312c06aac6b.png)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/d45ad777f4b29efa9867052df80e2b50dcabeeaa/uicomponent-compose/other/src/main/AndroidManifest.xml#L2

**Comment by ked4ma** [comment]
i'll try it!!

**Comment by takahirom** [comment]
Thanks! 🙌
