### ISSUE TITLE
Disable BuildConfig generate for compile time

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#125]
## Kind (Required)

- Improvement

 ## Overview (Required)

- If there is BuildConfig, the Java compilation will run, so I want to eliminate BuildConfig in the module.

 ## Links	

-

**Comment by takahirom** [comment]
You don't have to change the android module.

**Comment by tkmusic1976** [comment]
I wanna try it ✋

**Comment by takahirom** [comment]
Thanks! Assigned!
