### ISSUE TITLE
Keep the splash screen finished through screen rotation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#126]
## Kind (Required)

- Improvement

https://user-images.githubusercontent.com/1386930/109384087-d6d98180-792d-11eb-94a6-fe8e0ef79413.mp4

 ## Overview (Required)

- Probably we can use savedInstanceState for this

 ## Links	
- https://developer.android.com/jetpack/compose/state#restore-ui-state

**Comment by fornewid** [comment]
🙋‍♂️

**Comment by ymnder** [comment]
Thank you! We assigned this issue to you. 😄
