### ISSUE TITLE
Keep selected tab through screen rotation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#127]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Since this is the state of FeedScreen, it may be possible to keep it in ViewModel

 ## Links	

-

**Comment by Index197511** [comment]
I would like to challenge this issue.　@takahirom

**Comment by mhidaka** [comment]
@Index197511 please challenge it🚀  We assigned you 👍
