### ISSUE TITLE
Don't emit an error when an API that creates an account returns 409

### ISSUE THREAD

**Issue by jmatsu** [DroidKaigi/conference-app-2021#131]
## Kind (Required)

- Improvement

 ## Overview (Required)

- `POST /accounts` returns 409 if the user already exist on the server-side, so it's okay to suppress it and pass through the process.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/03d10c3b3f8414e18a7173ad4c15b8b4a057d2c7/data/api/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/AuthApi.kt#L45

**Comment by RyuNen344** [comment]
@jmatsu 
i wanna try this(sorry for lately mention....)
