### ISSUE TITLE
Build error : FakeNewsViewModel.kt: (46, 13): @exhaustive when is not exhaustive

### ISSUE THREAD

**Issue by adakoda** [DroidKaigi/conference-app-2021#144]
**Overview (Required)**
- Build error : FakeNewsViewModel.kt: (46, 13): @Exhaustive when is not exhaustive

**Steps To Reproduce**

1. Check out repository which version is 393f8ab57b8fdedee1c7c3393f50a61eb75bc543 2021/02/28 10:33:52
2. Build
3. Build will be failed. The messeage is bellow.
```
conference-app-2021\compose-uicomponent\src\main\java\io\github\droidkaigi\confsched2021\news\ui\news\FakeNewsViewModel.kt: (46, 13): @Exhaustive when is not exhaustive!
```

**Expected behavior**

- Build success.
- When I added following place holder, Build was succeded.
```
                is NewsViewModel.Event.OnHideSnackbarMessage -> {
                }
```

**Screenshots**
- N/A

**Env:**
 - Android Studio Arctic Fox | 2020.3.1 Canary 8
   - Build AI-0203.7148.57.2031.7165533, build on February 24, 2021
   - Runtime version: 11.08+10-b944.6842174 amd64
   - VM: OpenJDK 64-Bit Server VM by N/A

**Additional context**
- N/A

**Comment by adakoda** [comment]
One more things... (Same reasson: It seems that OnHideSnackbarMessage should be implemented.)

```
conference-app-2021\compose-uicomponent\src\main\java\io\github\droidkaigi\confsched2021\news\ui\news\NewsScreen.kt: (77, 42): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public operator fun <T, R> DeepRecursiveFunction<TypeVariable(T), TypeVariable(R)>.invoke(value: TypeVariable(T)): TypeVariable(R) defined in kotlin
```

**Comment by takahirom** [comment]
The file (FakeNewsViewModel.kt) should have been deleted... 👀 
https://github.com/DroidKaigi/conference-app-2021/tree/main/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder

**Comment by takahirom** [comment]
Maybe you can see the old files for some reason? 💭

**Comment by adakoda** [comment]
You are right.

I checked out the latest version again (28b8fc89d750b8b8a2e987b02450e52bdc37da06 2021/02/28 11:50:06), There is nothing problem.

Probably this issue was cause by my mistakes...

**Comment by takahirom** [comment]
Thank you for tryng!!🙌
