### ISSUE TITLE
Highlighted item  in Navigation Drawer according to the currently selected destination

### ISSUE THREAD

**Issue by Dai1678** [DroidKaigi/conference-app-2021#163]
## Kind (Required)

- Improvement

 ## Overview (Required)
Now the Home item is always highlighted in Navigation Drawer.

<img src="https://user-images.githubusercontent.com/19250035/109411386-13b47f80-79e5-11eb-81d7-345ce0dae439.gif" width=300>

How about making it the item is highlighted according to the currently selected destination?
For example, this is what the DroidKaigi2020 app looks like.

https://user-images.githubusercontent.com/19250035/109412185-e3231480-79e9-11eb-9ca3-761ee52bb425.mp4

 ## Links	

- https://developer.android.com/jetpack/compose/navigation?hl=ja#bottom-nav

**Comment by Dai1678** [comment]
@takahirom 
Can you please check this issue?
I'd like to try if everything is ok.

**Comment by takahirom** [comment]
Thank you for opening the issue! OK! Please try it 👍
