### ISSUE TITLE
Use Preview○○ for BackLayerContent Preview

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#165]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I want to unify the naming convention for Preview method names.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/8750f69558fb71383c958421236d71ffa05e27a5/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/BackLayerContent.kt#L73

**Comment by kaleidot725** [comment]
🙋‍♂️

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
