### ISSUE TITLE
Create blank iOS App project

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#166]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I'm not familiar with iOS apps, but I'd like to have an app base that uses the Swfit UI. At this point, it's okay if "Hello world" is displayed in the Swift UI.

 ## Links	

-

**Comment by yutaabe200** [comment]
@takahirom 
I would love to contribute, so please tell me the repository🙏

**Comment by takahirom** [comment]
I'll write a little tomorrow morning.🙏

**Comment by takahirom** [comment]
@yutaabe200 
* About this app
This is a Feeder app as described in the Readme.

* Technology
Once in this issue, I feel like creating an empty project using SwiftUI.
I would like to install iOS apps like the following projects in 2020.
https://github.com/DroidKaigi/conference-app-2020/tree/master/ios-base

This repository is considering using Kotlin Multiplatform classes for API and Repository. (Kotlin Multiplatform classes are also available on other platforms)

**Comment by yutaabe200** [comment]
@takahirom 
Thank you for the explanation.
Is the place to create "https://github.com/DroidKaigi/conference-app-2021/tree/main/ios"?

**Comment by takahirom** [comment]
I think it's good!
