### ISSUE TITLE
Apply "Navigation Drawer" screen design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#17]
## Overview (Required)
The title says everything.
Make it previewable(Prease add `@Preview` methods) and try to implement it paying attention to [state hoisting](https://developer.android.com/jetpack/compose/state#stateless-composables).
## Links
https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app
There are some parts where the design size is not accurate. Use 4dp * x size and similar Material components.
Please log in to see the size on the design.

**Comment by Dai1678** [comment]
@takahirom 
I will try this issue!

**Comment by takahirom** [comment]
Thanks!  The navigation drawer is also an important feature you often see! Assigned!🙌

**Comment by Dai1678** [comment]
@takahirom 
Could I download icons at 24dp from Figma?
Some of the icons can be used from Vector Asset in Android Studio, but for example the podcast icons are original and should be downloaded from Figma.
I'm not used to using Figma, so please let me know.

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Probably you can export SVG and it can import from Android Studio 👀 
Maybe you need to log in?
![image](https://user-images.githubusercontent.com/1386930/109409861-799b0a00-79d9-11eb-82c3-f08483fd5d1f.png)

**Comment by Dai1678** [comment]
I logged in to Figma and I can find icon.
But when I press the Export button, show Export failed.

<img width="1274" alt="スクリーンショット 2021-02-28 15 37 22" src="https://user-images.githubusercontent.com/19250035/109410084-0a261a00-79db-11eb-8e35-4758bdeefd12.png">

I was able to export the data named `Vector`, but the sizes are different.
I would like to have the icon data sliced at 24dp×24dp if possible.

<img width="1233" alt="スクリーンショット 2021-02-28 15 43 27" src="https://user-images.githubusercontent.com/19250035/109410176-c089ff00-79db-11eb-9b68-6e110bb67aca.png">

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
If you use Android Vector Drawable, it may be faster to download it from the following. You need to make sure it's the same design, but it seems faster than calling a designer. 🙇 
https://material.io/resources/icons/?style=baseline

**Comment by Dai1678** [comment]
The following icons have already been downloaded from Android Vector Drawable and they work fine.
- android icon
- contributor icon
- staff icon
- settings icon
- home icon (already exist in project)

However, these icons were not available in the Android Vector Drawable
- blog icon
- video icon
- podcast icon

Will icon datas be updated?

**Comment by takahirom** [comment]
How about doing the following?  
1 Implement that part empty and merge.  
2 I contact the designer and apply the image as another issue.

**Comment by Dai1678** [comment]
OK!  I'll continue with the implementation.

**Comment by takahirom** [comment]
@nontan Hello! I want to export the following 24dp x 24dp svg image. Do you know how to do it with Figma?
blog icon
video icon
podcast icon

**Comment by takahirom** [comment]
It seems that 16x20 svg images can be downloaded now.
![image](https://user-images.githubusercontent.com/1386930/109411043-840dd180-79e2-11eb-8312-be97cf050bdc.png)
