### ISSUE TITLE
Handling about MultiLangText model

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2021#174]
## Kind (Required)

- Improvement

 ## Overview (Required)

We've introduced MultiLangText to handle multi-language.
But we don't support displaying English text yet.

https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt#L91

 ## Links	

We can reference a implementation of the previous version of the conference app.
https://github.com/DroidKaigi/conference-app-2020/blob/master/model/src/jvmMain/kotlin/Lang.kt

https://github.com/DroidKaigi/conference-app-2020/blob/2c703ff896b9b58f07300d1c55b2d622c19203a1/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/LocaledString.kt

-

**Comment by yetanothercheer** [comment]
🙋🏻‍♂️

**Comment by tomoya0x00** [comment]
Thanks! Assigned 🙏
