### ISSUE TITLE
Post DroidKaigi logo image to "About This App" screen

### ISSUE THREAD

**Issue by hotatekaoru** [DroidKaigi/conference-app-2021#177]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Post DroidKaigi logo image to "About This App" screen and fix TODO comment

 ## Links	
- Figma: https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=0%3A1
<img width="338" alt="スクリーンショット 2021-02-28 21 09 50" src="https://user-images.githubusercontent.com/5081402/109417986-512b0400-7a09-11eb-8292-8df2e503365d.png">

- TODO code: https://github.com/DroidKaigi/conference-app-2021/blob/19576a0af53bc1cbf9a5aa0a8e3895de7112dd80/uicomponent-compose/other/src/main/java/io/github/droidkaigi/feeder/core/AboutThisApp.kt#L50-L51

**Comment by mightyfrog** [comment]
I'll take this one.

**Comment by mhidaka** [comment]
@mightyfrog thank you for your quick works! assigned 😃
