### ISSUE TITLE
Implement FakeViewModel and FakeViewModelTest for "Staff" screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#18]
## Overview (Required)
I want to make app "Testable & Previewable & Faster debug" as in https://github.com/DroidKaigi/conference-news-app-2021#testable--previewable--faster-debug .
That's why I want Fake to behave as much as possible with a real ViewModel. So add FakeViewModel and the corresponding tests.
## Links
https://github.com/DroidKaigi/conference-news-app-2021/blob/main/uicomponent-compose/news/src/main/java/io/github/droidkaigi/confnews2021/staff/news/FakeNewsViewModel.kt

**Comment by tfandkusu** [comment]
🙋

**Comment by mhidaka** [comment]
Thank you for standing as a contributor, We just assigned you 😉
