### ISSUE TITLE
Implement "Staff" screen without design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#19]
Blocked by #18 

## Overview (Required)
Since we need to display the information, we need to create classes for ViewModel, Repository, and API for that.
Please refer to the existing implementation and implement it.
This time there is no need for DB cache.
The API documentation can be found below.
## Links
https://droidkaigi.stoplight.io/docs/ssot-api/openapi/reference/external.v1.yaml

**Comment by tfandkusu** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍

**Comment by tfandkusu** [comment]
I have question about API.
I understood this issue needs API server implementation to get staff list and [this document](https://droidkaigi.stoplight.io/docs/ssot-api/openapi/reference/external.v1.yaml/paths/~1staff/get) describes its endpoint.
But the endpoint https://ssot-api-staging.an.r.appspot.com/staff responds 404 error.
Does I need to wait its API server implementation ?

**Comment by tfandkusu** [comment]
On second thought, ViewModel and its test don't need the API implementation. 
I'll proceed with this issue.

**Comment by takahirom** [comment]
I'm sorry, I think it's probably not implemented yet. Is it possible to create a fake api response and proceed with the implementation? 🙇

**Comment by tfandkusu** [comment]
Thanks for the reply. I will create a fake API response.
