### ISSUE TITLE
Use same compose version for library and compiler

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#190]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Maybe you can declare the version in Dep.kt and use it throughout the app.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/main/buildSrc/src/main/java/Dep.kt#L7-L16
- https://github.com/DroidKaigi/conference-app-2021/blob/0f42f6898c2be402e101157b490513da06ce1ca8/build.gradle#L5
- https://github.com/DroidKaigi/conference-app-2021/blob/d5f412259a82de8c829adab12eb6f7dc24137b13/uicomponent-compose/feed/build.gradle#L30

**Comment by risako070310** [comment]
🙋🏻‍♀️

**Comment by yurihondo** [comment]
Thanks! assigned!
