### ISSUE TITLE
Add line breaks for each parameter

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#191]
## Kind (Required)

- Improvement

 ## Overview (Required)

- The title says everything. Please see link.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/pull/186#discussion_r584393295

**Comment by tmk815** [comment]
🙋‍♂️

**Comment by tomoya0x00** [comment]
Thanks! Assigned ❤️

**Comment by takahirom** [comment]
Probably we should add an option for ktlint.
Can you add this? `.userData([android: "true"])`
https://github.com/diffplug/spotless/issues/750

**Comment by tmk815** [comment]
Can I use ktlint("0.39.0").userData([android: "true"]) in build.gradle?

**Comment by takahirom** [comment]
Yes! Please 🙏
