### ISSUE TITLE
Keep selected tab through rotation at OtherScreen

### ISSUE THREAD

**Issue by Index197511** [DroidKaigi/conference-app-2021#197]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Since this is the state of OtherScreen, it may be possible to keep it in ViewModel

 ## Links	

-

**Comment by sobaya-0141** [comment]
:raising_hand:

**Comment by sobaya-0141** [comment]
It looks issue already resolved

**Comment by takahirom** [comment]
Thanks for reporting!
