### ISSUE TITLE
Make the tab selected in the drawer open in FeedScreen

### ISSUE THREAD

**Issue by Index197511** [DroidKaigi/conference-app-2021#198]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Now when I select a tab from the drawer, it opens the Home tab every time. Please make sure that the tab selected from the drawer is opened in FeedScreen.

 ## Links	

-

**Comment by takahirom** [comment]
Probably this working on https://github.com/DroidKaigi/conference-app-2021/pull/196

**Comment by Index197511** [comment]
Should this issue be closed?

**Comment by takahirom** [comment]
Thank yok!
