### ISSUE TITLE
Make the tab selected in the drawer open in OtherScreen

### ISSUE THREAD

**Issue by Index197511** [DroidKaigi/conference-app-2021#199]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Now when I select a tab from the drawer, it opens the Home tab every time. Please make sure that the tab selected from the drawer is opened in OtherScreen.

 ## Links	

-

**Comment by ShebangDog** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned ❤️
