### ISSUE TITLE
Apply "Staff" screen design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#20]
Blocked by #18 

## Overview (Required)
The title says everything.
Make it previewable(Prease add `@Preview` methods) and try to implement it paying attention to [state hoisting](https://developer.android.com/jetpack/compose/state#stateless-composables).
## Links
https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app
There are some parts where the design size is not accurate. Use 4dp * x size and similar Material components.
Please log in to see the size on the design.

**Comment by mkano9** [comment]
Hi @takahirom I would love to pick this one up :)

**Comment by takahirom** [comment]
Hi @mkano9 ! Thank you every year! I assigned you! 👍
