### ISSUE TITLE
getDefaultLocale by platform implementation

### ISSUE THREAD

**Issue by RyuNen344** [DroidKaigi/conference-app-2021#200]
## Kind (Required)
- Other

 ## Overview (Required)

- Pure kotlin code is preferable for common modules.
- https://github.com/DroidKaigi/conference-app-2021/pull/195/files/0c217968280001a98c0664d445654608e6f421b6#r584475947
- I think it needs expect/actual fun

 ## Links	

- [kotlin natvie mapping](https://kotlinlang.org/docs/native-objc-interop.html#mappings)

**Comment by takahirom** [comment]
For now, just implement it in the main directory for Android in the same way, and you should be able to do it easily with expect actual.
https://kotlinlang.org/docs/mpp-connect-to-apis.html
https://github.com/DroidKaigi/conference-app-2021/blob/bdc87a890ec901c95493ef7787ac7fed84b916c3/data/api/src/main/java/io/github/droidkaigi/feeder/data/request/DevicePostRequest.kt#L3

**Comment by RyuNen344** [comment]
thanks for link to right reference 🙇

**Comment by Gazyu** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
