### ISSUE TITLE
Create the screen structure for iOS App

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#201]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, there is a blank screen. Can you create a feed and other screens?
- There is no need to adapt the design. It is only necessary to have a blank screen and only the screen structure.

 ## Links	

- Blank project: https://github.com/DroidKaigi/conference-app-2021/pull/193#issuecomment-787765954
- Android Design: https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app

**Comment by kagemiku** [comment]
Could I work on this issue?

**Comment by takahirom** [comment]
You seem to have iOS experience and are very grateful. Thank you! Assigned. I look forward to working with you. 👍
