### ISSUE TITLE
Move androidx.appcompat:appcompat:1.2.0 to Dep.kt

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#202]
## Kind (Required)

- Improvement

 ## Overview (Required)

- The title says everything. Please see link 🙏 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/f0267c32b8acb5f6f60a10e674c4cce858d9008d/uicomponent-compose/core/build.gradle#L47
- https://github.com/DroidKaigi/conference-app-2021/blob/main/buildSrc/src/main/java/Dep.kt#L19

**Comment by akihiro-n** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
