### ISSUE TITLE
Use English for Navigation Drawer text

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#203]
## Kind (Required)

- Improvement

 ## Overview (Required)

I talked with the designer.

DroidKaigiとは -> ABOUT
コントリビューター -> CONTRIBUTOR
スタッフ -> STAFF
設定 -> SETTING

 ## Links	

-

**Comment by akihiro-n** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned ❤️
