### ISSUE TITLE
Delete unnecessary placeholder

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#206]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Delete this and please check this screen.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/ed7f3543dc841122ff1d453b393fc2a3af711078/uicomponent-compose/other/src/main/java/io/github/droidkaigi/feeder/other/OtherScreen.kt#L90

**Comment by sobaya-0141** [comment]
:raising_hand:

**Comment by mhidaka** [comment]
It's fun! we just assigned you 👍

**Comment by sobaya-0141** [comment]
I tried remove `Box(modifier = Modifier.height(1.dp)) `

As a result, occur this error`java.lang.IllegalArgumentException: The initial value must have an associated anchor.`

Please let me know if I'm approaching this wrong.

**Comment by takahirom** [comment]
Thank you for investigating. 🙏 
Perhaps this is currently necessary.
I would like to create an issue to add a comment as another issue
