### ISSUE TITLE
Implement FakeViewModel and FakeViewModelTest for "Contributor" screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#21]
## Overview (Required)
I want to make app "Testable & Previewable & Faster debug" as in https://github.com/DroidKaigi/conference-news-app-2021#testable--previewable--faster-debug .
That's why I want Fake to behave as much as possible with a real ViewModel. So add FakeViewModel and the corresponding tests.
## Links
https://github.com/DroidKaigi/conference-news-app-2021/blob/main/uicomponent-compose/news/src/main/java/io/github/droidkaigi/confnews2021/staff/news/FakeNewsViewModel.kt

**Comment by tick-taku** [comment]
Hi! I want to try ✋
Please give me some times.

**Comment by mhidaka** [comment]
Sure! we always welcome your contribution. I just assigned you 👍
