### ISSUE TITLE
Remove divider displayed above the first item in feed lists

### ISSUE THREAD

**Issue by kafumi** [DroidKaigi/conference-app-2021#211]
## Kind (Required)

- Improvement

## Overview (Required)

A divider is displayed above the first item in feed list. This divider might make the boundary between the front layer and the back layer of backdrop looks "blurred" unexpectedly. It would be nice to remove it.
<img width="300" alt="device-2021-03-01-224020" src="https://user-images.githubusercontent.com/12084705/109505947-763e7600-7ae0-11eb-974b-96fe8d698f34.png">

## Links	

The divider is not displayed in Figma as well.
https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=1%3A1159

**Comment by takahirom** [comment]
I didn't notice it 👍 Thank you!

**Comment by takahirom** [comment]
Probably here.
It was implemented a long time ago, but there is a better way. 👀 
https://github.com/DroidKaigi/conference-app-2021/blob/7a907ac9602267443265a912744d7c69ef121e48/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedScreen.kt#L220

**Comment by sobaya-0141** [comment]
:raising_hand:

**Comment by takahirom** [comment]
Thanks! Assigned!
