### ISSUE TITLE
Fix padding when side navigation bar

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#212]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There is an inserter in this project, so please use it.
- https://chrisbanes.github.io/accompanist/insets/
![image](https://user-images.githubusercontent.com/1386930/109506197-b867b780-7ae0-11eb-97b9-bb912517504f.png)

 ## Links	

-

**Comment by fornewid** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned!
