### ISSUE TITLE
Use common logo image

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#213]
## Kind (Required)

- Improvement

 ## Overview (Required)

- In this PR we added two vector drawable. But we can use uicomponent-compose:core module.
in uicomponent-compose:feed
![image](https://user-images.githubusercontent.com/1386930/109508283-0a114180-7ae3-11eb-9067-12bfe8421c8a.png)
in uicomponent-compose:other
![image](https://user-images.githubusercontent.com/1386930/109508436-36c55900-7ae3-11eb-8f93-5424688c9310.png)

- Please move logo image to core module and delete toolbar_droidkaigi_logo.xml in each module.
![image](https://user-images.githubusercontent.com/1386930/109507829-7a6b9300-7ae2-11eb-9f59-2eea696c0b14.png)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/pull/207/files#diff-dce5360d6a559c632a27f2f7cdc879e58be67f63fa38626f9202a56ab3ca1ca7R1
- https://github.com/DroidKaigi/conference-app-2021/pull/207/files#diff-d0d1d0b77d25ddcac6a552a5cb63e5538b1c06e10557247304ed5d698dc58c43R1

**Comment by sobaya-0141** [comment]
:raising_hand:

**Comment by takahirom** [comment]
Thanks as always!! Assigned!
