### ISSUE TITLE
Implement "Contributor" screen without design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#22]
Blocked by #21 

## Overview (Required)
Since we need to display the information, we need to create classes for ViewModel, Repository, and API for that.
Please refer to the existing implementation and implement it.
This time there is no need for DB cache.
The API documentation can be found below.
## Links
https://droidkaigi.stoplight.io/docs/ssot-api/openapi/reference/external.v1.yaml

**Comment by RyuNen344** [comment]
@takahirom 
I wanna try this!

**Comment by takahirom** [comment]
It seems that fake's ViewModel is required for this function, so you will be based on this PR, but is that okay? 👀  I'll assign it for the time being! 👍 
https://github.com/DroidKaigi/conference-app-2021/pull/224

**Comment by RyuNen344** [comment]
thank you for assign 😆 

>It seems that fake's ViewModel is required for this function, so you will be based on this PR, but is that okay?

I understand that! I'm watching that issue and starting to ready for implement 🏃

**Comment by RyuNen344** [comment]
Hasn't the server API been implemented yet・・・?

**Comment by takahirom** [comment]
Sorry. Probably not yet.. Can you create and use a fake API response? 🙇
