### ISSUE TITLE
Can we use common artifact for Arbor?

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#228]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We use JVM artifact. But Probably In recent Kotlin MPPs, you can only refer to common artifact.
- Like `const val abor = "com.ToxicBakery.logging:arbor:1.35.72"`
- 
- Please delete "com.ToxicBakery.logging:arbor-android" and "com.ToxicBakery.logging:arbor-jvm" dependency and use "com.ToxicBakery.logging:arbor" 🙏 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/pull/221/files#diff-0f9d3ee70139178b0d6cca6bf4a909174a00934c74f3dc32c6afca2ed335d647R104

**Comment by akihiro-n** [comment]
🙋‍♂️

**Comment by mhidaka** [comment]
Thank you! Assigned 🚀

**Comment by akihiro-n** [comment]
I added this library.
```com.ToxicBakery.logging:arbor:1.35.72```
But there was a problem.
```
Could not find com.ToxicBakery.logging:arbor:1.35.72.
Required by:
    project :data:api
```

I'm sorry. Do you know how to solve this problem?

**Comment by takahirom** [comment]
Sorry, can you try com.ToxicBakery.logging:common? 🙇 
https://search.maven.org/search?q=g:com.ToxicBakery.logging

**Comment by akihiro-n** [comment]
Thank you. I will try.
