### ISSUE TITLE
Use const value for route string

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#229]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We are using `feed/` `other/`
- Can you use top-level const value for this in AppContent?
- https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/AppContent.kt#L72

 ## Links	

-

**Comment by k-tomoyasu** [comment]
🙋

**Comment by takahirom** [comment]
Thanks!Assigned!
