### ISSUE TITLE
Apply "Contributor" screen design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#23]
Blocked by #21 

## Overview (Required)
The title says everything.
Make it previewable(Prease add `@Preview` methods) and try to implement it paying attention to [state hoisting](https://developer.android.com/jetpack/compose/state#stateless-composables).
## Links
(TBD)

**Comment by RyuNen344** [comment]
@takahirom 
I wanna try this!

**Comment by takahirom** [comment]
Sorry for late. Thanks, Assigned 👍
