### ISSUE TITLE
Switch status bar transparent when navigation drawer open

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#230]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, we use always semi-transparent background.
- But navigation drawer of material component android switch transparent and semi-transparent when open drawer.
- 
![image](https://user-images.githubusercontent.com/1386930/109596458-a5dd9480-7b59-11eb-91e3-0475daa9c261.png)

 ## Links	

-

**Comment by cheddar-dev** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍

**Comment by cheddar-dev** [comment]
I'm very sorry, something has come up at home and I won't be able to finish this task. 
So, I remove my assignment. 🙇‍♀️

**Comment by takahirom** [comment]
OK! Thank you for your challenge!

**Comment by tkhs0604** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks for challenge! Assigned 👍

**Comment by tkhs0604** [comment]
@takahirom 
I've tried this issue several times, but I could not resolve it.
So, I give up this issue. I am terribly sorry for commenting late.

**Comment by takahirom** [comment]
Thank you for your challenge! I look forward to your next challenge 👍

**Comment by yasuhiroki** [comment]
🙋‍♂️

**Comment by mhidaka** [comment]
@yasuhiroki Thank you for your ✋ ! We assigined.

**Comment by yasuhiroki** [comment]
note)
behavior images 
https://github.com/DroidKaigi/conference-app-2021/pull/410#issuecomment-817089830
