### ISSUE TITLE
Rename to onSelectTab to onSelectFeedTab

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#233]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Because there is onSelectOtherTab

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/AppContent.kt#L127

**Comment by akeybako** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍

**Comment by akeybako** [comment]
My work conflicts with current main branch.
I assume this issue has already been resolved.

**Comment by akeybako** [comment]
in https://github.com/DroidKaigi/conference-app-2021/pull/261
`onSelectTab ` was removed.

**Comment by takahirom** [comment]
Oh.. Sorry. I didn't notice it. 
I look forward to your next contribution!
