### ISSUE TITLE
Use material icon for navigation drawer image

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#237]
## Kind (Required)

- Improvement

 ## Overview (Required)
- Please use the material icon

- https://github.com/DroidKaigi/conference-app-2021/blob/5da442dafc34583249daf37c86a4f4fe1517686a/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/DrawerContent.kt#L46
・BLOG → text_snippet
・VIDEO → videocam
・PODCAST → mic_none

![image](https://user-images.githubusercontent.com/1386930/109651303-af8aea80-7ba1-11eb-8b77-d935fb0854d7.png)

![image](https://user-images.githubusercontent.com/1386930/109651348-c3cee780-7ba1-11eb-8f6c-ffdf42e6354e.png)

 ## Links	

-

**Comment by yonce3** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
