### ISSUE TITLE
DroidKaigi 2021 app is not listed in home launcher

### ISSUE THREAD

**Issue by kafumi** [DroidKaigi/conference-app-2021#238]
**Overview (Required)**

DroidKaigi 2021 app is not listed on home launcher.

**Steps To Reproduce**

1. Install DroidKaigi 2021 app via [DeployGate](https://dply.me/o701pp#install)
2. Go to home app

**Expected behavior**

- After step 1, "Open" button of the "DroidKaigi 2021" app should be enabled in DeployGate app
- After step 2, "DroidKaigi 2021" app is found from app list

**Screenshots**

https://user-images.githubusercontent.com/12084705/109651343-c0d3f700-7ba1-11eb-8b32-c650c0488098.mp4

**Env:**

- Device: Pixel 3a
- OS: 11
- App Version or the branch: latest beta of staging/refs/heads/main on DeployGate

**Additional context**

- The issue is reproduced as well when I built app and installed it via adb
- Probably the issue is caused because we set `<data>` along with action `MAIN` in the intent filter of `MainActivity`

**Comment by takahirom** [comment]
Critical :eyes:  I will look this :eyes:
