### ISSUE TITLE
Remove border of feed image

### ISSUE THREAD

**Issue by maho-ya** [DroidKaigi/conference-app-2021#240]
**Overview (Required)**
- The feed image has a border that is not in the design instructions and needs to be removed.

**Steps To Reproduce**

1. Launch App
2. Show home screen

**Expected behavior**
It is expected that there will be no border in the feed image.

**Screenshots**

Figma design | App 
:--: | :--:
<img width="143" alt="スクリーンショット 2021-03-02 21 12 36" src="https://user-images.githubusercontent.com/32348624/109647448-a5b2b880-7b9c-11eb-9080-8f4290dff628.png"> | <img width="143" alt="figma" src="https://user-images.githubusercontent.com/32348624/109646833-ecec7980-7b9b-11eb-97fa-b1b488412346.png">

**Env:**
 - Device: Pixel
 - OS: Android 8.0
 - master 9fe747b

**Additional context**
It has been discussed in the Issue below.
https://github.com/DroidKaigi/conference-app-2021/issues/88#issuecomment-788880361

**Comment by maho-ya** [comment]
@takahirom 
I understand. I will try this issue.

**Comment by takahirom** [comment]
Thanks! Assigned 👍
