### ISSUE TITLE
Delete compose_versoin

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#245]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  We can use Versions.compose for using places of compose_version
- 
 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/d0fdd62f14f833d413260ab5be8e316beeaaa841/build.gradle#L6

**Comment by fucchi-senpai** [comment]
Can I try it? 🙇

**Comment by mhidaka** [comment]
Sure, You should try it 👍  Assigned!
