### ISSUE TITLE
Add deeplink declaration in AndroidManifest.xml

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#246]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - I deleted data element. Because it is wrong and It removed this app's launcher icon. 
https://github.com/DroidKaigi/conference-app-2021/pull/241/files
 - It should be okay if you write it in android.intent.action.VIEW normally.

 ## Links	

- https://developer.android.com/training/app-links/deep-linking?

**Comment by RyuNen344** [comment]
sorry for enhancement bug.... Would you give a chance for fix it... 🙇

**Comment by takahirom** [comment]
I think the good thing about this app is that you can make a lot of breaking changes, so let's make a lot of aggressive changes!
