### ISSUE TITLE
Add preview for LandingScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#247]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please add a preview function for this screen

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/4d2556e2d4aa0ef89da9371f3c5208fcbdcdf42b/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/LandingScreen.kt

**Comment by sobaya-0141** [comment]
:raising_hand:

**Comment by KeithYokoma** [comment]
@sobaya-0141 Thanks! Go ahead and feel free to ask anything to us :)
