### ISSUE TITLE
Delete outdated comment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#248]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Now, we don't use the Deprecated function. so we can remove that 👍 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/8750f69558fb71383c958421236d71ffa05e27a5/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/LandingScreen.kt#L19

**Comment by tkhs0604** [comment]
🙋‍♂️ (My first time to contribute for open source project)

This means that we only have to delete "FIXME Deprecated" comment?

**Comment by takahirom** [comment]
Yes! it is!
Assigned!
