### ISSUE TITLE
Add night mode preview for FeedScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#249]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  The title says everything
- Probably You can do it with pass true to the theme. https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedScreen.kt#L272

 ## Links	

-

**Comment by BokaDaiki** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
