### ISSUE TITLE
Apply "About this app" screen design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#25]
## Overview (Required)
The title says everything.
Make it previewable(Prease add `@Preview` methods) and try to implement it paying attention to [state hoisting](https://developer.android.com/jetpack/compose/state#stateless-composables).
## Links
https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app
There are some parts where the design size is not accurate. Use 4dp * x size and similar Material components.
Please log in to see the size on the design.

**Comment by hotatekaoru** [comment]
🙋‍♂️ 
I want to challenge Jetpack Compose 💪

**Comment by takahirom** [comment]
Thank you for challenging!!🙏

**Comment by mhidaka** [comment]
Thanks, Go ahead!
