### ISSUE TITLE
Fix feed top items

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#259]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I see two identical items and it seems that there is no divider.
![image](https://user-images.githubusercontent.com/1386930/109816415-0e209900-7c74-11eb-955e-7634af70f4c5.png)

 - 

 ## Links	

-

**Comment by ttanaka330** [comment]
🙋

**Comment by satsukies** [comment]
@ttanaka330 
Thanks! Assigned👍
