### ISSUE TITLE
Implement answer survey item 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#262]
## Kind (Required)

- Improvement

 ## Overview (Required)

- You don't have to add it to the list of feeds for use with:
- https://github.com/DroidKaigi/conference-app-2021/issues/67
 - Please be able to check the screen in Preview.
![image](https://user-images.githubusercontent.com/1386930/109823713-85a5f680-7c7b-11eb-9a70-e0c00d164c2f.png)

 ## Links	

- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=0%3A1

**Comment by mattukouta** [comment]
I want to try it. 🙋‍♂️

Should I make a transition to link? Or is it only design?

**Comment by yurihondo** [comment]
@mattukouta 
Assigned 🙏 
Thank you for your cooperation！

**Comment by takahirom** [comment]
No need to handle button events!

**Comment by mattukouta** [comment]
OK. Thank you for your reply.
