### ISSUE TITLE
Remove unnecessary comments in FeedItem

### ISSUE THREAD

**Issue by maho-ya** [DroidKaigi/conference-app-2021#267]
**Overview (Required)**

Remove old comments to avoid confusion.

https://github.com/DroidKaigi/conference-app-2021/blob/61ac0bba6a309dc06dd7de04b88a46abe7219b0c/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt#L86

_Originally posted by @takahirom in https://github.com/DroidKaigi/conference-app-2021/pull/235#discussion_r586983842_

**Comment by maho-ya** [comment]
I'll try it.

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
