### ISSUE TITLE
Improve method to show divider

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2021#269]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, We're looping twice the size of the content to display the Divider in FeedScreen
- If we referred to the Jetsnack app, We can avoid it

### Our App
https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedScreen.kt#L235

![image](https://user-images.githubusercontent.com/5106629/109927258-43c29200-7d07-11eb-919d-f4bd9fb80a0c.png)

### In Jetsnack

- https://github.com/android/compose-samples/blob/main/Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/search/Results.kt#L76
- https://github.com/android/compose-samples/blob/main/Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/search/Results.kt#L97

![image](https://user-images.githubusercontent.com/5106629/109927328-5e950680-7d07-11eb-88f4-7415778d6445.png)

 ## Links

**Comment by mightyfrog** [comment]
I'll take care of it.

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
