### ISSUE TITLE
Use arbor android in android module

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#271]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - The abor android was deleted in the following pull request, but I want to use LogCatSeedling, so add abor android to the dependency with the "android" module and change it to use LogCatSeedling.
https://github.com/DroidKaigi/conference-app-2021/pull/265

 ## Links	

-

**Comment by yoshida0261** [comment]
🙋🏻‍♂️

**Comment by KeithYokoma** [comment]
@yoshida0261 Thanks! Assigned this issue to you so go ahead 👍

**Comment by takahirom** [comment]
Sorry. We will quit using arber.
Sorry for close this issue 🙏
