### ISSUE TITLE
implement Kotlin Native version of getDefaultLocale()

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#272]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - Please somehow use Kotlin Native to determine the locale for Japan or not. Perhaps the iOS development documentation will be helpful.
 - Add one actual function to iosMain and you're done.

You can check it by this.

./gradlew :model:compileKotlinIos

e: /Users/takahirom/git/connference-app-2021-news/model/src/commonMain/kotlin/io/github/droidkaigi/feeder/Locale.kt: (8, 12): Expected function 'getDefaultLocale' has no actual declaration in module <conference-app-2021:model> for Native

![image](https://user-images.githubusercontent.com/1386930/109970289-3a9de900-7d38-11eb-91b3-bd3a35016ecd.png)

 ## Links	

-

**Comment by myihsan** [comment]
I would like to try🙋‍♂️

**Comment by yurihondo** [comment]
@myihsan 
Sorry for late reply.
I assigned you to this issue!
Thank you for your cooperation.
