### ISSUE TITLE
Add a comment to OtherScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#273]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - This method is "stateless". So I want to add "stateless" comment for this method

OtherScreen
https://github.com/DroidKaigi/conference-app-2021/blob/93b26358ce69b21e45048b51d1789ee28b6b8d8e/uicomponent-compose/other/src/main/java/io/github/droidkaigi/feeder/other/OtherScreen.kt#L74

FeedScreen
https://github.com/DroidKaigi/conference-app-2021/blob/ad72af5346207ee059b12756a4a0c9bca19d0205/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedScreen.kt#L139
 ## Links	

- https://developer.android.com/jetpack/compose/state

**Comment by Takafumi-Orita** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
