### ISSUE TITLE
Move "about this app" screen to about package from staff package

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#274]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please move to io.github.droidkaigi.feeder.about

 ## Links	

-https://github.com/DroidKaigi/conference-app-2021/blob/31f9fff3c70dbcf71a590a6d41713492525bb2bd/uicomponent-compose/other/src/main/java/io/github/droidkaigi/feeder/staff/AboutThisApp.kt#L19

**Comment by YuheiKawakami** [comment]
🙋‍♂️

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
