### ISSUE TITLE
Add dark theme setting for settings screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#279]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - The night mode design has already been implemented. 
 - Last year's app may be helpful for implementing switching.
 - The design of the setting is similar to last year's design.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/pull/526/files

**Comment by ocuto** [comment]
🙋‍♂️

**Comment by KeithYokoma** [comment]
@ocuto Thank you, give it a shot!
