### ISSUE TITLE
Content no scrolls after switching tabs

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#282]
**Overview (Required)**
- 

**Steps To Reproduce**

1. Go to 'blog tab'
2. Click on 'home tab'
3. Scroll
4.  can't scroll

**Expected behavior**
Can scroll

**Screenshots**

https://user-images.githubusercontent.com/1386930/110193863-e3079680-7e79-11eb-9412-ae829415d81f.mp4

**Env:**
 - Device: Pixel3
 - OS: 11.0
 - App Version or the branch main

**Additional context**

**Comment by fornewid** [comment]
Probably, it may be related to [this issue](https://issuetracker.google.com/issues/176089198). 🙄 
https://issuetracker.google.com/issues/176089198

**Comment by anandwana001** [comment]
This is working for me.

**Comment by takahirom** [comment]
Thank you for reporting! I will close this issue 👍
