### ISSUE TITLE
Cool favorite toggle animation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#283]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Do you have any favorite animations?

 ## Links	

- https://developer.android.com/jetpack/compose/animation

**Comment by fornewid** [comment]
What do you think of this animation? 🤔
The source code is [here](https://github.com/fornewid/android-animation-11p-more/blob/end/sample/src/main/java/soup/animation/sample/widget/HeartAnimationView.kt).

🙋‍♂️ (If the animation below is okay)

https://user-images.githubusercontent.com/3405740/110206884-bc6e4d80-7ec3-11eb-8ac0-5b79d4aa49e3.mp4

**Comment by takahirom** [comment]
Looks good! But It uses Android View? 👀

**Comment by fornewid** [comment]
Yes, that's right.
I have to create a new one for Compose. 😄

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
I look forward to your implementation 😄
