### ISSUE TITLE
Fix naming for Preview method

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#285]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Use Preview〇〇 instead of ○○Preview

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/ee2c57aaba325c4e00bf4b371f1f34cdd6af53ef/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/AnswerSurveyItem.kt#L100

**Comment by yonce3** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
