### ISSUE TITLE
Show background for AnswerSurveyItem Preview

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#289]
## Kind (Required)

- Improvement

## Overview (Required)

- It's hard to see the preview now because the background isn't colored.
- - You can improve it by using AppThemeWithBackground(), so please try it.
![image](https://user-images.githubusercontent.com/1386930/110197164-0d168400-7e8d-11eb-89c5-744879df0957.png)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/efda223b22ac510b5ec4e6c53b1a2df98264d629/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/DrawerContent.kt#L207
- https://github.com/DroidKaigi/conference-app-2021/blob/ee2c57aaba325c4e00bf4b371f1f34cdd6af53ef/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/AnswerSurveyItem.kt#L101

**Comment by tommykw** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks Assigned!
