### ISSUE TITLE
Reload when clicking the action button in the error Snackbar

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#290]
## Kind (Required)

- Improvement

 ## Overview (Required)

- A reload button has already been added to the Snackbar, but the reload process itself is not implemented.
- https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/viewmodel/RealFeedViewModel.kt#L88
- reload feature added this PR
- https://github.com/DroidKaigi/conference-app-2021/pull/275

 ## Links	

-

**Comment by atsuya046** [comment]
I want to try 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
