### ISSUE TITLE
Get app version name on About this app screen

### ISSUE THREAD

**Issue by akihiro-n** [DroidKaigi/conference-app-2021#312]
## Kind (Required)
- Improvement

 ## Overview (Required)
- Related issue #308 
- Get app version name on About this app screen

**Comment by matsujun** [comment]
Ah... the "Related Issue" is not merged yet...

**Comment by mightyfrog** [comment]
I'll take care of it.

**Comment by t-nonomura** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍

**Comment by t-nonomura** [comment]
@tomoya0x00 
Thank you, but is a different person assigned?

**Comment by tomoya0x00** [comment]
@t-nonomura Oh, Sorry 🙇 Reassigned 👍
