### ISSUE TITLE
@Suppress("unused") to this property

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#315]
## Kind (Required)

- Improvement

 ## Overview (Required)

- for fixing inspection

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/34a1dd7363efc0875d49170c58783b69e0352718/android/src/test/java/io/github/droidkaigi/feeder/FeedItemViewModelTest.kt#L26

**Comment by yonce3** [comment]
🙋‍♂️
