### ISSUE TITLE
Add background to FeedItem preview

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#318]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It's hard to see the preview now because the background isn't colored.
- You can improve it by using AppThemeWithBackground(), so please try it.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/efda223b22ac510b5ec4e6c53b1a2df98264d629/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/DrawerContent.kt#L207

**Comment by a25max** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
