### ISSUE TITLE
Update Kotlin  1.4.30 -> 1.4.31

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#320]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We should update kotlin

 ## Links	

-

**Comment by akeybako** [comment]
🙋

**Comment by KeithYokoma** [comment]
@akeybako Thanks! I assigned this issue to you. Feel free to ask any questions you have 👍

**Comment by takahirom** [comment]
@akeybako Sorry. 🙇  I need to upgrade Kotlin to upgrade Compose, so I'll upgrade Kotlin together. We look forward to your next contribution. 👍

**Comment by akeybako** [comment]
OK!
I confused this error message of Compose Compiler.
`e: This version (1.0.0-alpha13) of the Compose Compiler requires Kotlin version 1.4.30 but you appear to be using Kotlin version 1.4.31 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).
`

Even though 1.0.0-alpha13 doesn't exist.
