### ISSUE TITLE
Delete unneeded comment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#322]
## Kind (Required)

- Improvement

 ## Overview (Required)

- The comments are below.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/b9534e910bbc98f8d3662186bc0547f048aa1e72/data/api/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/AuthApi.kt#L25-L27

**Comment by anandwana001** [comment]
I want to start contributing to this by this issue. Sending a PR for this.
