### ISSUE TITLE
Unit Test that the Favorite of FeedItem is reflected

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#324]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Check that what you passed in the argument is reflected.
![image](https://user-images.githubusercontent.com/1386930/110401402-daeb6900-80bc-11eb-843a-548608fc4548.png)

 ## Links	

- test sample : https://github.com/DroidKaigi/conference-app-2021/pull/310

**Comment by akihiro-n** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
