### ISSUE TITLE
Unit Test that the showMediaLabel parameter of the FeedItem is reflected

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#325]
## Kind (Required)

- Improvement

 ## Overview (Required)

- The title says everything
![image](https://user-images.githubusercontent.com/1386930/110401651-4df4df80-80bd-11eb-8856-7bc2568b12a2.png)

 ## Links	

- test sample : #310

**Comment by anandwana001** [comment]
I want to work on this @takahirom
