### ISSUE TITLE
Remove usages of `jcenter()`

### ISSUE THREAD

**Issue by anandwana001** [DroidKaigi/conference-app-2021#328]
## Kind (Required)

- Improvement

 ## Overview (Required)
Warning by Android Studio

```
Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'conference-app-2021', project ':android', project ':data', ...
Affected Modules: android
```

**Comment by takahirom** [comment]
Definitely 😄

**Comment by ykws** [comment]
🙋 

It looks good to just remove `jcenter()` from gradle, because the build was successful.

**Comment by satsukies** [comment]
@ykws 
That sounds good, assigned 👍 
We look forward to your contribution 😄

**Comment by punchdrunker** [comment]
#338 solved partially this issue. But some libs are still hosted on the only JCenter.
So we'll create some issues for the rest of the libraries hosted on JCenter for the future.
