### ISSUE TITLE
Add android test to CI

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#331]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We were adding android test . But we don't check its status by ci 😭 
- Please add it. 

 ## Links	

- We can refer compose-samples
- https://github.com/android/compose-samples/blob/main/.github/workflows/JetNews.yaml

**Comment by hkusu** [comment]
✋ Can I try this?

**Comment by satsukies** [comment]
@hkusu 
Of course, Thank you!
We assigned this issue to you 👍
