### ISSUE TITLE
Proposal about the design for the iOS app

### ISSUE THREAD

**Issue by myihsan** [DroidKaigi/conference-app-2021#334]
## Kind (Required)

Proposal / Discussion

 ## Overview (Required)

Is there any chance that we can have another design for the iOS app?

We can indeed use [material-components-ios](https://github.com/material-components/material-components-ios), but we cannot use it directly since it's implemented by _UIKit_ which is different from our current layout framework–_SwiftUI_.
It's possible to make it work in _SwiftUI_, but it will take many unnecessary efforts and face unexpected issues.

So I think it may be a good idea to have another design for iOS. It's not only for the development cost but also for the iOS users.

If it's possible, I would like to try to invite a designer to help us. It would be helpful to have the information below:
- Where can we find specification documents that the designer needs to refer to?
- Is there any schedule for design products?
- Is there any universal guideline for design?

 ## Links	

- An [issue](https://github.com/material-components/material-components-ios/issues/8508) about using material-components-ios in SwiftUI

**Comment by takahirom** [comment]
Thank you for your suggestion. I'll talk with the staff. 🙏

**Comment by takahirom** [comment]
I'm sorry to be late. I will report on the current situation for the time being.
I talked to the designer who designed Android for the time being, but it seems that it will take time to prepare the design, so it seems that it is not realistic to prepare the iOS design. She's also new to figma and wants to see the designs of other designers.
Therefore, it may be better to recruit designers at present.
Currently, I didn't expect them, so I don't have those documents.
Perhaps it is better to share what you want to hear at Meeting etc. with external designers, including designers who designed Android applications and engineers who understand iOS development.

**Comment by myihsan** [comment]
Thanks!
Let me ask designers in my company if they have interests.
Just to confirm, there is no reward for the design, right?
I am not sure if this is normal in the designer world, so I will point it out while asking them.

**Comment by takahirom** [comment]
I'm sorry, there is no reward.
I don't know if it's a reward, but I can only put the designer's name in the README.
https://github.com/DroidKaigi/conference-app-2021#designer

**Comment by myihsan** [comment]
The inviting is ongoing. Once there is one designer who raises his/her hand, let's schedule a meeting.

However, I found out that attending the meeting without some base information is already a hurdle for participation.
So it would be very helpful for the designers who have interests but not sure if they have enough time to answer the questions below as possible before the meeting.

- Work Period (deadline)
- Function list
- With or without a regular meeting
- Universal Design guideline (is there anything that should not change from the android design)

Especially the first two, I think.

**Comment by takahirom** [comment]
Thank you. I'll prepare it with the designer. 🙏

**Comment by takahirom** [comment]
I talked to the designer about this.

Work Period (deadline)
It hasn't been decided in particular, but it seems that contributors will easily gather within a month.

Function list
https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app
You can check the feed
You can check about this app
You can check the contributors
You can check the staff
You can check the settings
You can see the recruitment of questionnaires

With or without a regular meeting
There are no regular meetings, and they meet online if they need something.
Recently, about once a month.

Universal Design guideline (is there anything that should not change from the Android design)
I don't think it has to be perfectly aligned, but We are interested in Color and Shape. Other than that, it has not been decided. 

Color is shown in Figma (* Layer names are different ...)
https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=1072%3A420
The dark theme has not been designed, and the contributors make it on their own.

Shape
top left and bottom right corner cut
large component
32
small, medium
8

If you can make the design a designer, that's fine, but if you tell the Android designer the points to focus on iOS design, it will take time, but it seems that the designer who designed Android may be able to design it.
If saying this is likely to cause confusion, don't worry.


Work Period (deadline)
特に決まっていないが1ヶ月以内ぐらいだとコントリビューターが集まりやすそう

Function list
https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app
フィードを確認できる
このアプリについて確認できる
コントリビューターを確認できる
スタッフが確認できる
設定を確認できる
アンケートの募集が見られる

With or without a regular meeting
定例会議はなく、何か必要になれば集まっている。月一程度あるかないか。

Universal Design guideline (is there anything that should not change from the Android design)
完璧に揃えなくてはいけないと思ってはいないが、関心事としてColorとShapeがある。それ以外は決まっていない。

https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=1072%3A420
ColorはFigmaにある（※レイヤーの名前がバラバラになっている…
ダークテーマについてはデザインはできておらず、コントリビューターが作っている。

Shape
top left and bottom right corner cut
large component
32
small, medium
8

もしデザインをデザイナーにしていただけるならそれで良いが、iOSのデザインに寄せるポイントを教えていただければ、時間はかかるがAndroidのデザインをしたデザイナーがデザインすることもできるかもしれないそうです。
もしこれを言うことで混乱を招きそうであれば言わなくても大丈夫です。

**Comment by myihsan** [comment]
Thanks a lot!
Let me share with the designers.

> もしデザインをデザイナーにしていただけるならそれで良いが、iOSのデザインに寄せるポイントを教えていただければ、時間はかかるがAndroidのデザインをしたデザイナーがデザインすることもできるかもしれないそうです。

なるほど、もしこちらに余裕かつ興味があるデザイナーがいなければ、ぜひこちらの協力をさせていただきたいです🙇‍♂️

**Comment by myihsan** [comment]
Here is one designer who raises her hand!
Her current situation is as below:
- Busy before April
  - Like to join if it's fine to change the deadline to the end of April
- Prefer text-based communication

Is it ok for you guys?

**Comment by takahirom** [comment]
Thank you! It's okay.

**Comment by myihsan** [comment]
Thanks for the chance!
This would be a significant improvement for the iOS development, which would attract more iOS engineers who have interests in KMM and SwiftUI.

I will contact you as soon as there is any progress from the designer.

**Comment by myihsan** [comment]
FYI, the designer is going to start the design this weekend.

**Comment by takahirom** [comment]
Thank you! 🎉 
I'd like to ask if it's better to do something like onboarding MTG or ask a text-based question what you want to know. 👀

**Comment by myihsan** [comment]
It seems like the information here https://github.com/DroidKaigi/conference-app-2021/issues/334#issuecomment-800724327 is enough for now.
Is there any news?

The design will share the intermediate design once she is ready.

**Comment by takahirom** [comment]
Thank you! There are no other changes.
Please tell me anytime. 🙏

**Comment by myihsan** [comment]
Here is one quick question.

Will there a native detail page for the feed?
This may affect the design.
- Web page: No need to use [Navigation Bar](https://developer.apple.com/design/human-interface-guidelines/ios/bars/navigation-bars/) because of the specification of `SFSafariViewController` which displays web pages.
- Native page: Prefer to use [Navigation Bar](https://developer.apple.com/design/human-interface-guidelines/ios/bars/navigation-bars/) to provide universal user experience, but have more restrictions for design.

**Comment by takahirom** [comment]
The detail page does not exist.
On Android, it is displayed on the Web using Chrome Custom Tab.
I think it will probably be Safari View Controller on iOS.

**Comment by nobonobopurin** [comment]
Hello, I'm Choi, a designer. I am happy to participate in this project as a designer.
The UI for the iOS app is complete, so now it can be shared.

 Link : [https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-iOS?node-id=0%3A1](url)

The colors and shapes have been adapted to Android UI, but the major changes are as follows.

-  Use Bottom navigation instead of Navigation Drawer
-  Display D-Day information on Home

Is it ok for you guys?

**Comment by takahirom** [comment]
Thank you! I'll check! 
@myihsan 
Please comment if you have any advice from the perspective of an iOS engineer.

**Comment by takahirom** [comment]
I checked a little. I think it's easy to understand and has a very good design.
It seems that the composition of the screen has changed quite a bit.

One thing I'm worried about is that it may not be possible to use common logic between iOS and Android.
I'm sorry I couldn't share this issue because I couldn't anticipate it. I think I should have asked you to share it when I started making it a little.
However, even if the common logic cannot be used for the UI logic, I think that the others can be used, and I think it is better to proceed for the time being. 👍

**Comment by myihsan** [comment]
> Please comment if you have any advice from the perspective of an iOS engineer.

I have done it before the sharing above. 
The only remaining issue is the loading screen better not cover the full screen.

I will try to ask more iOS engineers for advice next weak.

> One thing I'm worried about is that it may not be possible to use common logic between iOS and Android.

I think it also has a good side for practice the design for the shared KMM module.

**Comment by nobonobopurin** [comment]
Is it okay to modify the design so that the loading screen no longer covers the full screen?
I forgot to change to a Skeleton screen.

**Comment by myihsan** [comment]
It may not be necessary after I demonstrate the way we implement Skeleton screen by SwiftUI.
So please keep your time for some new proposal or advice from other iOS engineers next week🙇‍♂️

**Comment by myihsan** [comment]
@takahirom 
The review by six iOS engineers in YUMEMI Inc., including me, has ended.
The conclusion is that an iOS engineer can implement this design with [SwiftUI-Introspect](https://github.com/siteline/SwiftUI-Introspect) (A library that helps us deal with some iOS components that hard to custom in SwiftUI) without too many efforts. So this design looks good for us.

Is our review enough for you?
If so, it may be time to update README so that we can close this issue.

**Comment by takahirom** [comment]
Thank you! I will close the issue and put it in the README. 🎉 
@nobonobopurin 
I'd like to list it below as a designer. Is there any link you would like to use?
https://github.com/DroidKaigi/conference-app-2021#designer

**Comment by nobonobopurin** [comment]
@takahirom 
Thank you! 🎉
Please use the link below:
[](https://github.com/nobonobopurin)

**Comment by takahirom** [comment]
Thank you! I will update README 👍
