### ISSUE TITLE
DI framework for iOS targets

### ISSUE THREAD

**Issue by watanavex** [DroidKaigi/conference-app-2021#353]
## Kind (Required)
- Proposal

 ## Overview (Required)
Why not use a DI framework for iOS targets?
Koin and Kodein are compatible with KMM.
As it is now, I think Hilt is fine for Android target. 
Because this app has to learn to experience Hilt as well.

 ## Links	
- https://insert-koin.io
- https://github.com/Kodein-Framework/Kodein-DI

**Comment by watanavex** [comment]
I'll work on it as per my proposal!

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
