### ISSUE TITLE
Proposal the feature to Swipe and switch tabs

### ISSUE THREAD

**Issue by akihiro-n** [DroidKaigi/conference-app-2021#355]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)
I wanted to achieve a better UX and came up with this idea.
I have implemented a simple demo of this feature.  
If you like, I want to incorporate this function.
I want to hear your opinion.

<img src="https://user-images.githubusercontent.com/30426163/111031378-a83dc980-844a-11eb-8098-1f8f127966af.gif" width="300" />

**Comment by takahirom** [comment]
I think it is good! If something goes wrong, I think it's okay if we revert. 👍

**Comment by akihiro-n** [comment]
Thank you !
I will try this task 🙋
