### ISSUE TITLE
Remove Ktor from model module dependencies

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#356]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We put Ktor in the model module to parse the URL.
I think that you can prevent the reference in the model module by parsing the URL when creating the class.
- https://github.com/DroidKaigi/conference-app-2021/pull/348/files#diff-1fcd54ff839a5ae2ba602b56b215fe6c8202961396253435a3d6995814aa5d35R18-R19

 ## Links	

-

**Comment by akihiro-n** [comment]
🙋

**Comment by mhidaka** [comment]
Thank you for your quick work 👍
