### ISSUE TITLE
Separate MediaPlayer from RealFeedViewModel

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#357]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Putting it in makes the FeedViewModel bigger, and its functionality is completely platform-dependent, so I'd like to separate it.
 - How about FmPlayerViewModel etc.?

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/pull/348/files#diff-869051b887b09c40b445ee5ea2a14f99e5035876760b5468626d45138366a25eR49

**Comment by akihiro-n** [comment]
🙋

**Comment by satsukies** [comment]
@akihiro-n  Thanks! We assigned this issue to you 👍
