### ISSUE TITLE
Make tabs scrollable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#36]
## Kind (Required)

- Improvement

 ## Overview (Required)
News and other screens have tabs, but they can't be scrolled. Make it scrollable like a design

![image](https://user-images.githubusercontent.com/1386930/107894745-fe1a7100-6f73-11eb-8ce5-c0645c902e67.png)

 ## Links	

-

**Comment by NUmeroAndDev** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned! 📜
