### ISSUE TITLE
Rename FeedTabs to FeedTab

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#360]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  This is because it is strange that the parent class of each tab has multiple meanings of "Tabs".

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedScreen.kt#L56

**Comment by ked4ma** [comment]
:hand:

**Comment by takahirom** [comment]
Thanks as always!
