### ISSUE TITLE
Map exception to AppError in NetworkService

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#362]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There is an AppError class for the in-app, but it is not currently used.
 - To use this, enclose each method of NetworkService in try-catch and `throw e.toAppError()` in the catch.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/pull/361/files#diff-e1f7b74b80b19f6c4b01811cf17b69bff5dbd293c391fdab9b563e2a1cea614dR24-R37

**Comment by ked4ma** [comment]
:hand: 
i'll do after #363 (i felt it may be easier to do this after that. / prevent code confliction)
