### ISSUE TITLE
Bring authApi processing to NetworkService

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#363]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - Currently, the processing of authApi is included in all network communication methods as follows.
 - I would like to solve this process by deleting the AuthApi class and bringing it to networkService.

```kotlin
authApi.authenticated {
        networkService.get<ContributorsResponse>(
            "https://ssot-api-staging.an.r.appspot.com/contributors"
        ).toContributorList()
    }
```

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/pull/361/files#diff-e1f7b74b80b19f6c4b01811cf17b69bff5dbd293c391fdab9b563e2a1cea614dR24
- https://github.com/DroidKaigi/conference-app-2021/blob/093b7836dab4b450276e5a52164b0407be791498/data/api/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/AuthApi.kt#L15

**Comment by ked4ma** [comment]
:hand:

**Comment by takahirom** [comment]
Thanks! Assigned!
