### ISSUE TITLE
Show error snackbar when refresh error

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#364]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - `try-catch` the following and send it to the `effectChannel`.
https://github.com/DroidKaigi/conference-app-2021/blob/2aca45d4be764b67dd9b56057b9fededc3939532/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/viewmodel/RealFeedViewModel.kt#L45

```kotlin
effectChannel.send(FeedViewModel.Effect.ErrorMessage(error.e))
```

 - This can be checked using airplane mode.

 ## Links	

-

**Comment by ked4ma** [comment]
:hand:

**Comment by takahirom** [comment]
Thanks Assisted!
