### ISSUE TITLE
Improve DroidKaigi FM play/pause button

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2021#365]
## Kind (Required)

- Improvement

 ## Overview (Required)

- In dark theme, the play/pause button  is hard to find
- We want to improve it
  - For example, specify the button color to white by tint and add a semitransparent black circle background behind the button
  - Perhaps, we don't need to change the color depending on the normal/dark theme

### Normal theme

<img src="https://user-images.githubusercontent.com/5106629/111065270-2f974580-84fc-11eb-9553-294fa8ad77d3.png" width=400>

### Dark theme

<img src="https://user-images.githubusercontent.com/5106629/111065215-f3fc7b80-84fb-11eb-82b2-c5c15264b322.png" width=400>

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedItem.kt#L195

**Comment by jihoi-kang** [comment]
I wanna take this ✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
@jihoi-kang Thanks! Assigned 👍

**Comment by warahiko** [comment]
I want to try this 🤚

**Comment by takahirom** [comment]
Thanks! Assigned 👍
