### ISSUE TITLE
Increase the size of the first item on the Home tab.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#37]
## Kind (Required)

- Improvement

## Overview (Required)

- The title says everything

![image](https://user-images.githubusercontent.com/1386930/107894900-97e21e00-6f74-11eb-9ef4-a6a02c22057d.png)

 ## Links	

https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app
There are some parts where the design size is not accurate. Use 4dp * x size and similar Material components.
Please log in to see the size on the design.

**Comment by hiesiea** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
