### ISSUE TITLE
Crash on low API level terminals

### ISSUE THREAD

**Issue by hkusu** [DroidKaigi/conference-app-2021#373]
**Overview (Required)**
- Crash on low API level terminals

**Steps To Reproduce**

Boot on API level 23 device.

**Expected behavior**

**Screenshots**

<img width="800" alt="スクリーンショット 2021-03-15 1 26 51" src="https://user-images.githubusercontent.com/6157540/111076017-d942fa80-852d-11eb-947e-1ef2069ea40a.png">

**Env:**

Reproduce on all API level 23 devices

**Additional context**

Probably related to: https://github.com/Kotlin/kotlinx-datetime#using-in-your-projects

Due to this issue, Android Test also crashes on lower devices: https://github.com/DroidKaigi/conference-app-2021/blob/de419ff444be83b94b1347d6597a90f36306dcab/.github/workflows/android-test.yml#L14

**Comment by hkusu** [comment]
I will fix it 💪

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
