### ISSUE TITLE
Link privacy policy

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#377]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There is a link to the privacy policy in AboutThisApp, but it's not working. Please change so that you can transition to the link from there.

 ## Links	

- http://www.association.droidkaigi.jp/privacy.html

**Comment by KKusumi** [comment]
✋

**Comment by k-shinn** [comment]
🙋‍♂️

**Comment by mhidaka** [comment]
Thank you! We assigned you.
