### ISSUE TITLE
Show Snackbar above the navigation bar

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#378]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I just don't know how to do it. Is there a good solution?
![image](https://user-images.githubusercontent.com/1386930/111092288-ffda5300-8578-11eb-957e-e224ea441776.png)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/pull/366

**Comment by ked4ma** [comment]
:raised_back_of_hand:

**Comment by takahirom** [comment]
Thanks!
