### ISSUE TITLE
The theme is not reflected when returning from the setting to the fixed theme to the system theme

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#379]
**Overview (Required)**
- 

**Steps To Reproduce**

https://user-images.githubusercontent.com/1386930/111092426-68293480-8579-11eb-93f9-2d760e2c3df6.mp4

**Expected behavior**
If it's clear

**Screenshots**
If applicable

**Env:**
 - Device: Pixel3
 - OS: 11.0
 - App Version or the branch main

**Additional context**
Any other notes

**Comment by anandwana001** [comment]
Working correctly for me. @takahirom 

![droidkaigi_theme_settings](https://user-images.githubusercontent.com/25057618/116773546-71ac2480-aa73-11eb-8441-2df28fbf76a8.gif)

**Comment by takahirom** [comment]
I think it was fixed with the Compose update. Thank you!
