### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#38]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- Currently there is no dark mode design. Can someone give it a try? 🌔 

 ## Links	

https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app
There are some parts where the design size is not accurate. Use 4dp * x size and similar Material components.
Please log in to see the size on the design.

**Comment by kafumi** [comment]
Could I try this issue? I will prepare color palette of dark theme based on [2020 app implementation](https://github.com/DroidKaigi/conference-app-2020) and [2020 design kit](https://www.figma.com/file/RPPQQRys8IubNShKan8c2Z/DroidKaigi-2020-App-Design-Kit) in addition to [2021 UI spec](https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app).

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
