### ISSUE TITLE
Cute Android robot animation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#380]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/111092561-bf2f0980-8579-11eb-99af-edfaae01ea98.png)

 ## Links	

-

**Comment by b4tchkn** [comment]
I want to challenge🙋‍♂️

**Comment by KeithYokoma** [comment]
@b4tchkn Thanks for applying! I assigned this issue to you 👍
