### ISSUE TITLE
Display like audio spectrum during DroidKaigi FM playback

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#381]
## Kind (Required)

- Improvement

 ## Overview (Required)

- You don't have to actually make it from the sound. Is it possible to display an animation on the image during playback?

 ## Links	

-

**Comment by akihiro-n** [comment]
🙋‍♂️

**Comment by akihiro-n** [comment]
I'm really sorry. :crying_cat_face: 
I tried a little, but
I didn't seem to be able to achieve the animation I expected, so please remove my assign. :cry:

**Comment by takahirom** [comment]
It's okay! We are waiting for your other challenge again! 👍

**Comment by akihiro-n** [comment]
Thank you! 😸 
If I come up with a good animated idea, I might try again. :smirk_cat:

**Comment by rmakiyama** [comment]
🙋🏻

**Comment by mhidaka** [comment]
Thanks! we assigned you.
