### ISSUE TITLE
Remove Unused Import

### ISSUE THREAD

**Issue by anandwana001** [DroidKaigi/conference-app-2021#384]
## Kind (Required)

Choose the suitable template if exists.
- Improvement

 ## Overview (Required)

- Remove the unused import

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/de419ff444be83b94b1347d6597a90f36306dcab/uicomponent-compose/other/src/main/java/io/github/droidkaigi/feeder/about/AboutThisApp.kt#L27

**Comment by takahirom** [comment]
Thank you for reporting!

**Comment by KKusumi** [comment]
✋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
