### ISSUE TITLE
Apply filter design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#387]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  Filter design is improved
![image](https://user-images.githubusercontent.com/1386930/111401711-28935180-870d-11eb-8b37-7d23709b6268.png)
![image](https://user-images.githubusercontent.com/1386930/111401801-537da580-870d-11eb-80b6-e3d315504d5c.png)

 - https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=1072%3A420
 - **The All filter checkbox is present in the design but is not needed.**

 ## Links	

-

**Comment by ked4ma** [comment]
✋

**Comment by yurihondo** [comment]
@ked4ma 
Thanks! Assigned🙇
