### ISSUE TITLE
Change design when filtered

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#388]
## Kind (Required)

- Improvement

 ## Overview (Required)
 - no animation needed
 - filter not exits
![image](https://user-images.githubusercontent.com/1386930/111401903-8e7fd900-870d-11eb-9ef6-225b4d24a557.png)

 - filter exits
![image](https://user-images.githubusercontent.com/1386930/111401858-74de9180-870d-11eb-8ff6-337da7a33418.png)

 ## Links	

- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=1072%3A420

**Comment by 175atsu** [comment]
✋
i want to try

**Comment by takahirom** [comment]
Thanks! Assigned 👍
