### ISSUE TITLE
Switch only the theme once

### ISSUE THREAD

**Issue by ShebangDog** [DroidKaigi/conference-app-2021#394]
**Overview (Required)**

**Steps To Reproduce**

1. Go to Setting
2. Click on Theme
3. Clink on any theme 
4. Clink on any theme
4. See app color

**Expected behavior**
Change to the selected theme

**Screenshots**

https://user-images.githubusercontent.com/38370581/111781982-d2383580-88fb-11eb-8ebc-4952c6beffc9.mp4

**Env:**
 - Device: Pixel3a
 - OS: 11.0
 - App Version or the branch [master]

**Additional context**

It is resolve to change compose version to "1.0.0-beta01" from "1.0.0-beta02"

**Comment by takahirom** [comment]
Probably related to this?
https://github.com/DroidKaigi/conference-app-2021/issues/379


> It is resolve to change compose version to "1.0.0-beta01" from "1.0.0-beta02"

Oh! Thank you for your information!

**Comment by ShebangDog** [comment]
Yes, it is related.
Sorry, I missed it.
