### ISSUE TITLE
How to solve flow on iOS?

### ISSUE THREAD

**Issue by watanavex** [DroidKaigi/conference-app-2021#395]
## Kind (Required)

- Discussion

 ## Overview (Required)
- Subscribing to flow from swift is a hassle
- It cannot be unsubscribed
- I think [this flow wrapper](https://github.com/touchlab/SwiftCoroutines/blob/master/shared/src/iosMain/kotlin/co/touchlab/swiftcoroutines/SwiftCoroutines.kt) is a good way.
- If you have any other ideas, I would love to know!

 ## Links	
- https://github.com/touchlab/SwiftCoroutines

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
I think the method using suspend wrapper is good.👍
 A library called koru automates the task of creating a wrapper for it, but on the scale of DroidKaigi you may want to write a wrapper each time.

**Comment by watanavex** [comment]
> A library called koru automates the task of creating a wrapper for it, but on the scale of DroidKaigi you may want to write a wrapper each time.

I think the same thing.
Thank you!

**Comment by takahirom** [comment]
Thank you! Please let me know if there is anything else.
