### ISSUE TITLE
We can update flipper to 0.82.1 because the issue is solved.

### ISSUE THREAD

**Issue by clockvoid** [DroidKaigi/conference-app-2021#403]
## Kind (Required)

Choose the suitable template if exists.

- Improvement

 ## Overview (Required)

- Related with this comment:
[<img src="https://user-images.githubusercontent.com/6965122/112849310-e6dab180-90e3-11eb-9790-7c916273ca7b.png" width="350" />](https://github.com/DroidKaigi/conference-app-2021/blob/3420c1deaa4f1211e5f90f34db379b24399911fa/buildSrc/src/main/java/Dep.kt#L129)
- When I saw https://github.com/facebook/flipper/issues/1968, the issue has been solved.
  - I tried flipper 0.82.1 and that seems working well.

 ## Links	

- #91

**Comment by takahirom** [comment]
Thank you for reporting!  I attached a pr welcome label.
