### ISSUE TITLE
Support push notifications

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#41]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please support firebase push. 
- Please put the token to the server with onNewToken.

 ## Links	

- https://firebase.google.com/docs/cloud-messaging/android/client
- https://droidkaigi.stoplight.io/docs/ssot-api/openapi/reference/external.v1.yaml/paths/~1devices~1%7BdeviceId%7D/put

**Comment by RyuNen344** [comment]
@takahirom 
if only android app, I wanna try this!

**Comment by takahirom** [comment]
This issue is for the android app only! 👍 Assigned 🤖
