### ISSUE TITLE
Remove `All` toggle

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#412]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Because it is different from the behavior of the check box.
All toggles are not needed. It exists in Figma, but the designer just can't erase it because she doesn't have time. 🙏 
![image](https://user-images.githubusercontent.com/1386930/114955976-cf981400-9e98-11eb-8710-191f793514a4.png)

 ## Links	

-

**Comment by ked4ma** [comment]
i'll do this since i had added this checkbox :raised_back_of_hand:

**Comment by takahirom** [comment]
Assigned! And I will look at your implementation 😄
