### ISSUE TITLE
When filtered, the number of applicable items is displayed even if it is closed.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#413]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, the number of corresponding items disappears when the filter is closed.
- I want to judge the display based on whether it is filtered or not.

https://user-images.githubusercontent.com/1386930/114956267-7b416400-9e99-11eb-9f5f-e8e62a0d4517.mp4

 ## Links	

-

**Comment by ked4ma** [comment]
:raised_back_of_hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
