### ISSUE TITLE
Make the image smaller when filtered

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#414]
## Kind (Required)

- Improvement

 ## Overview (Required)

- When not fileterd
![image](https://user-images.githubusercontent.com/1386930/114956587-294d0e00-9e9a-11eb-9bb8-1b3ee6e187f9.png)
- When filtered
![image](https://user-images.githubusercontent.com/1386930/114956571-1d614c00-9e9a-11eb-8191-025318c794ff.png)

 ## Links	

-

**Comment by fummicc1** [comment]
I would like to undertake this isuue! 
Please tell me how much smaller a filtered image is than initial one, or show me a figma link?🙏

**Comment by takahirom** [comment]
Thank you for checking this!
It looks 20dp 📏 
![image](https://user-images.githubusercontent.com/1386930/115168597-81804c00-a0f6-11eb-9ebf-a3be8e142f8c.png)
https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=1485%3A417
