### ISSUE TITLE
Drawable-night is not accessible

### ISSUE THREAD

**Issue by anandwana001** [DroidKaigi/conference-app-2021#425]
**Overview (Required)**
- In the dark mode, images are not coming from the `drawable-nigth`. 

**Steps To Reproduce**

1. Go to Settings and change theme to dark
2. Go to about and see the image logo

**Expected behavior**
In the dark theme image should come from `drawable-nigth`

**Screenshots**
<img src="https://user-images.githubusercontent.com/25057618/116775006-f7cd6880-aa7d-11eb-9924-64d3662e3aaa.png" width=230 height=430 />

**Env:**
 - Device: Pixel XL
 - OS: @* API level

**Additional context**
Approaches solve:
1. We can introduce `RealAboutThisAppViewModel` and `AboutThisAppViewModel` and bring the ThemeRepository data to the `AboutThisApp` screen and use the view model in the `fun WhatIsDroidKaigiComponent` and based on theme, get the image. But, in this approach, we cannot access an image from `drawable-night`, so we need to rename the image to `logo_night` and put it in the drawable folder only. 
2. We can use `ContextCompat` and get the drawable, but then we need to get the drawable id and pass it to the `painterResource` which is a bit complex.

**Comment by anandwana001** [comment]
@takahirom Let me know your thoughts on this.

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
I see, the configuration of Activity is in light mode, but it seems to be happening because it is in night mode in the application.
I think it may be possible to change the theme of Activity by using AppCompatDelegate.

```kotlin
    AppCompatDelegate.setDefaultNightMode(
        when (state.theme) {
            Theme.SYSTEM -> AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM
            Theme.DARK -> AppCompatDelegate.MODE_NIGHT_YES
            Theme.LIGHT -> AppCompatDelegate.MODE_NIGHT_NO
            null -> AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM
        }
    )
```
