### ISSUE TITLE
Merge Dep.kt `Jetpack` and `AndroidX` Object

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#434]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It's almost the same, so it doesn't matter which one, but I want to put them together.

https://github.com/DroidKaigi/conference-app-2021/blob/main/buildSrc/src/main/java/Dep.kt#L110-L122
https://github.com/DroidKaigi/conference-app-2021/blob/main/buildSrc/src/main/java/Dep.kt#L28-L33

 ## Links	

-

**Comment by emusute1212** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned
