### ISSUE TITLE
[iOS] Re-initialize iOS Project

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#441]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Re-initialize iOS Project to satisfy following requirements.
  - Use "Swift Package Manager Project Definition".
    - If this project should divide configuration(such as `Debug` and `Production` ), please divide Xcode Project.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/issues/439#issuecomment-848549228
- [Swift PMとマルチプロジェクトでBuild Configurationをクリーンに保つ](https://www.notion.so/date/Swift-PM-Build-Configuration-4f14ceac795a4338a5a44748adfeaa40)

**Comment by takahirom** [comment]
👀
