### ISSUE TITLE
What we need with Kotlin Multiplatform for iOS

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#445]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

 - I want to sort out what we need a little.

according to https://github.com/DroidKaigi/conference-app-2021/pull/415#issuecomment-824710629

- Implement Suspend Wrapper.
https://touchlab.co/kotlin-coroutines-rxswift/

- Implement Authenticator in Swift

Authenticator

```kotlin
package io.github.droidkaigi.feeder

data class User(
    val idToken: String?
)

interface Authenticator {
    suspend fun currentUser(): User?
    suspend fun signInAnonymously(): User?
}
```

 ## Links	

-

**Comment by takahirom** [comment]
@watanavex 
Is this the same recognition? 🙏

**Comment by watanavex** [comment]
@takahirom  Thank you!
- Implement Suspend Wrapper
[Suspend wrapper has already been implemented.](https://github.com/DroidKaigi/conference-app-2021/tree/main/ios-framework/src/iosMain/kotlin/io/github/droidkaigi/feeder/repository)
This is a good match with the README described by @ry-itto, and I am aware of no problems.

- Implement Authenticator in Swift
We need this. I want to do it!!

**Comment by watanavex** [comment]
@takahirom 
How do I get the GoogleService-Info.plist?
(In the context of Android, it is google-services.json)

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
I'm checking it, so please wait for a while.

**Comment by takahirom** [comment]
@watanavex 
Please use this 🙏 
[GoogleService-Info-Stating-Debug.plist.zip](https://github.com/DroidKaigi/conference-app-2021/files/6602154/GoogleService-Info-Stating-Debug.plist.zip)
