### ISSUE TITLE
[iOS] Create common components

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#446]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This issue can work after #443 merged.
- Create common components in `Component` module.
  - Tags
  - Message Bar
  - Cards
    - Small
    - Medium
    - Large
- Implement action with callbacks. Such as `**tapAction: @escaping () -> Void`.
- Please implement with Xcode Previews 👍🏼 

 ## Links	

- [Figma](https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-(iOS)?node-id=140%3A6667)

**Comment by ostk0069** [comment]
@ry-itto I wanna take it ✋

**Comment by ry-itto** [comment]
@ostk0069 
Thanks! Assigned 👍🏼
