### ISSUE TITLE
[iOS] Change TabBar tint color

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#447]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This issue can work after #443 merged.
- Currently, the tabBar tint color doesn't match the design. Please match that tint color to design.

 ## Links	

- [Figma](https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-(iOS)?node-id=18%3A2302)

**Comment by shun-sasano** [comment]
I would like to do this task！🙏

**Comment by ry-itto** [comment]
@shun-sasano 
Thanks! 
Assigned 👍🏼 


Currently, the use of colors is not working in the main branch, so I would appreciate it if you could incorporate [this change](https://github.com/DroidKaigi/conference-app-2021/pull/454) and work on it 🙏🏼

**Comment by shun-sasano** [comment]
@ry-itto 
Thank you!
understood!👍
