### ISSUE TITLE
[iOS] Create About Screen (UI) - staff/contributor -

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#448]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This issue can work after #443 merged.
- Please implement about screen UI (staff/contributor view only).
- No need to implement the part that calls the API through KMM module.

 ## Links	

- [Figma](https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-(iOS)?node-id=140%3A8797)

**Comment by shun-sasano** [comment]
I would like to do this task！🙋‍♂️

**Comment by ry-itto** [comment]
@shun-sasano 
Thanks!Assigned 👍 :+1

**Comment by ry-itto** [comment]
@shun-sasano 
I changed this issue to implement `staff/contributor` part only.

I would appreciate it if you could recognize it 🙏🏼
