### ISSUE TITLE
[iOS] Create Setting Screen (UI)

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#449]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This issue can work after #443 merged.
- Please implement Setting Screen UI.
- No needed to implement  logic (Changing Language, Toggle theme).

 ## Links	

- [Figma](https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-(iOS)?node-id=140%3A8797)

**Comment by fummicc1** [comment]
I would like to try this task✋

**Comment by ry-itto** [comment]
Thanks! I will assign this issue to you 👍🏼
