### ISSUE TITLE
[iOS] Create Media List Screen Frame

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#450]
## Kind (Required)
- Improvement

 ## Overview (Required)

- This issue can work after #443 merged.
- Please implement Media - List Screen.
  - It's ok to implement List items(Cards) with empty views. (This components will be created by #446 )

 ## Links	

- [Figma](https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-(iOS)?node-id=140%3A8797)

**Comment by myihsan** [comment]
I would like to try🙋‍♂️

**Comment by ry-itto** [comment]
Thanks! Assigned 👍🏼
