### ISSUE TITLE
[iOS] Create Favorites Screen Frame

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#451]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This issue can work after #443 merged.
- Please implement Favorites Screen Frame.
  - It's ok to implement items(Cards) with empty views.

 ## Links	

- [Figma](https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-(iOS)?node-id=140%3A8797)

**Comment by ostk0069** [comment]
I wanna take this!

**Comment by ry-itto** [comment]
Thanks! Assigned 👍🏼
