### ISSUE TITLE
[iOS & KMM] Generate KMM module as xcframework

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#459]
## Kind (Required)

- Proposal / Discussion
- Improvement

 ## Overview (Required)

- Currently, the KMM module is generated as `.framework`. In iOS App, use `xcframework` is better way. 
- In this iOS project management way, it can use `xcframework` only.
- According to above, it is necessary to generate KMM module as `xcframework`. 

There are two solutions.
1. Generate `xcframework` with gradle step.
  - It's not clear, but I think this plugin may be useful.
    - https://github.com/ge-org/multiplatform-swiftpackage
2. Generate `xcframework` with shell script.
  - Using generated `.framework` and combine them.

I want to decide the generating way. 🙏🏼 

 ## Links	

This discussion may be related. (Cocoapods part is not needed.)
- https://discuss.kotlinlang.org/t/distribute-kmm-shared-as-xcframework/20163

**Comment by ry-itto** [comment]
@takahirom 
How about this?

**Comment by takahirom** [comment]
I think we can do it by creating a Gradle task.
You can define this in ios-framework and run it by `./gradlew ios-framework:linkDebugXCFrameworkIos`

```
    val linkDebugXCFrameworkIos by tasks.creating(Exec::class.java) {
       exec.group = "build"
       val frameworkArm64 = kotlin.targets.getByName<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget>("${name}Arm64").binaries.getFramework(mode)    
       val frameworkX64 = kotlin.targets.getByName<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget>("${name}X64").binaries.getFramework(mode)
       exec.dependsOn(frameworkArm64.linkTask, frameworkX64.linkTask)
       commandLine 'xcrun xcodebuild -create-xcframework -framework ${frameworkArm64.outputDirectory.absolutePath}/'
    }
```

**Comment by ry-itto** [comment]
I see. I will try this 🙏🏼 
Thanks!
