### ISSUE TITLE
[iOS] Create About - What is DroidKaigi Screen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#460]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please create "What is DroidKaigi" screen without screen transition in `AboutFeature` module.
- Open links are not needed.
- Please implement with Localizable strings.
- Debug screen with Xcode Previews.

 ## Links	

- https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-(iOS)?node-id=140%3A8797

**Comment by Tech-Nayuta** [comment]
I'd like to try this issue 👍

**Comment by ry-itto** [comment]
Thanks! Assigned 👍🏼
