### ISSUE TITLE
[iOS] Access color defined in Asset with `Color` directly

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#461]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, to apply asset color to SwiftUI View is a little redundancy like this `Color(AssetColor.primary.color)` because `AssetColor.primary.color` 's type is `UIColor`.
- Please be able to use asset color with type `Color` which can use in SwiftUI directly.
- Please implement with editing [`swift5.stencil`](https://github.com/DroidKaigi/conference-app-2021/blob/main/ios/templates/xcassets/swift5.stencil)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/pull/457#discussion_r643334333

**Comment by ostk0069** [comment]
@ry-itto 
I wanna take this!

**Comment by ry-itto** [comment]
thanks!assigned!
