### ISSUE TITLE
[iOS] Update SwiftGen XCFileLists

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#462]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, `Localizable.strings` input/output statement is not specified.
- Please add `Localizable.strings` input/output statement to current XCFileList files.

### How to fix this
- Run `make run-swiftgen-generate-xcfilelists` only.
  - Two files will change ( `XCFileLists/SwiftGenInput.xcfilelist` and `XCFileLists/SwiftGenOutput.xcfilelist`)

 ## Links	

-

**Comment by fucchi-senpai** [comment]
Can I try this? 🙋

**Comment by ry-itto** [comment]
Yes! Of course! 
Thanks! Assigned 👍🏼
