### ISSUE TITLE
[iOS] Setup iOS GitHub Actions workflow (Danger)

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#475]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please setup iOS CI environment with Danger SwiftLint

 ## Links	

-

**Comment by 417-72KI** [comment]
I am providing my own GitHub Action (https://github.com/417-72KI/danger-swiftlint).
Can I use it?

**Comment by ry-itto** [comment]
@417-72KI 
It looks good!

> Can I use it?

Of course 👍🏼
