### ISSUE TITLE
[iOS] Use SwiftUI-Introspect

### ISSUE THREAD

**Issue by myihsan** [DroidKaigi/conference-app-2021#483]
## Kind (Required)

Proposal / Discussion

## Overview (Required)

I propose to use [SwiftUI-Introspect](https://github.com/siteline/SwiftUI-Introspect) in iOS project.

Firstly, I need it to set `searchController` for #450.

Secondly, the implementation of `NavigationBarConfigurator` is a little risky for now.
It seems like designed for the similar purpose of `navigarionController?.navigarionBar` (current navigation stack), but the implementation is using `UINavigationBar.appearance()` (throughout the whole app), and will recover the previous settings when the view disappeared (like `navigationItem`).
And it has an unexpected behavior to recover the previous settings when push a new view, though it may not be a problem with the current design. 

With SwiftUI-Introspect, we should be able to achieve everything we want effortlessly.

### Throughout the whole app

```swift
UINavigationBar.appearance()
```

### Current navigation stack

```swift
.introspectNavigationController { navigationController in
    navigationController.navigationBar
}
```

### Current view controller

```swift
.introspectViewController { viewController in
    viewController.navigarionItem
}
```

If it's fine to use SwiftUI-Introspect, I would like to submit a PR using it to update the current implementation for `UINavigationBar` 🙋‍♂️

 ## Links	

- https://github.com/siteline/SwiftUI-Introspect

**Comment by ry-itto** [comment]
@myihsan 
Good idea! It's fine! Please 🙏
