### ISSUE TITLE
[iOS] Make Navigation better with Router

### ISSUE THREAD

**Issue by ostk0069** [DroidKaigi/conference-app-2021#493]
## Kind (Required)

- Discussion

 ## Overview (Required)
- Currently, we are using The Composable Architecture for iOS App Architecture. If theres any idea to improve navigation, let discuss.
- I have an idea to implement something like https://github.com/SwiftUIX/Coordinator but this does not really fit with TCA.
- Directly creating PR is also welcome.

 ## Links	
- https://github.com/pointfreeco/swift-composable-architecture
- https://github.com/SwiftUIX/Coordinator

**Comment by myihsan** [comment]
Could you please describe the current issues in the Composable Architecture about navigation?
If no navigation is too complicated, it's enough for me using `State` and `IfLetStore`.

**Comment by ostk0069** [comment]
> Could you please describe the current issues in the Composable Architecture about navigation?
If no navigation is too complicated, it's enough for me using State and IfLetStore.

Sorry for the late response.
Actually we don't have any problem with navigation right now. My idea was to discuss whether we could find any improvement for navigation which we will have in media list to media detail navigation by calling like [this](https://github.com/SwiftUIX/Coordinator#integrate-your-coordinator) 

(自分の英語だと伝わっているのか怪しいので日本語で捕捉します)
このissueを作成した意図としては現状SwiftUIの画面遷移の呼び出しはあんまり綺麗にできないと感じています。
Routerクラスみたいなものを作成し、[この](https://github.com/SwiftUIX/Coordinator#integrate-your-coordinator) のように呼び出しができないか模索するための議論ができればと思い作成しました。またそれには設計として採用しているTCAの思想とずれない形で実装することも同時に必要だと考えています。今回の仕様だと画面遷移を使用する箇所は少ないので通常の方法でも問題はありませんがOSSとして作ってる以上はより良くできればと思った次第です。もちろん必要ないと言う意見が多ければこのissueはcloseするつもりです。

**Comment by myihsan** [comment]
Thank you for your explanation!
I can understand your point, but when it comes to combining with TCA, we may need to define what we actually want to achieve, for example, define the issues to resolve.
Because TCA is managing navigation by states, and we can navigate with one action, it's a little confuse to me what to improve.
