### ISSUE TITLE
[iOS] Show more readable build log

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#494]
## Kind (Required)

- Improvement

 ## Overview (Required)

- In generated build-log such as `make build-modules` output is difficult to read and too long.
- Please apply build-log formatter to build-log such as `xcpretty` `xcbeautify` .

 ## Links	

-

**Comment by ostk0069** [comment]
@ry-itto 
I wanna take this ✋

**Comment by ry-itto** [comment]
Thanks! Assigned 👍🏼
