### ISSUE TITLE
[iOS] Show `What is DroidKaigi` banner in About Screen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#500]
## Kind (Required)
- Improvement

 ## Overview (Required)

- Please show `What is DroidKaigi` banner` in About Screen
- Customize `MessageBar` in `Component` module to make it possible to use `View` in content.

 ## Links	

- https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-iOS?node-id=140%3A5877

**Comment by daichi77** [comment]
🙋

**Comment by ry-itto** [comment]
@daichi77 
Thanks! Assigned 👍🏼

**Comment by ry-itto** [comment]
@daichi77 
How about this? 🙏🏼

**Comment by daichi77** [comment]
@ry-itto I'm sorry, I will make a pull request today. If I can't do it today, I'll give up
