### ISSUE TITLE
[iOS] Transition to Setting Screen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#501]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please make transitioning to SettingScreen.
- Please implement without thinking about https://github.com/DroidKaigi/conference-app-2021/issues/493 once.

 ## Links	

-

**Comment by Tech-Nayuta** [comment]
I'd like to try this issue after finished #506

**Comment by ry-itto** [comment]
thanks! assigned 👍 :+1

**Comment by Tech-Nayuta** [comment]
Thank you!

**Comment by Tech-Nayuta** [comment]
@ry-itto 
I pulled latest main branch and execute ```make run-swiftgen``` , it can't be worked. 
The following error has occurred.
```conference-app-2021/ios/Tools/.build/checkouts/10: fatal error: could not build module 'Darwin' ```
Do you know the solution for this problem?

**Comment by Tech-Nayuta** [comment]
Resolved this problem!
There was the cache  ```ios/Tools/.build``` left
Thank you.
