### ISSUE TITLE
[iOS] Create Media Detail Screen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#503]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please create Media/Detail Screen.
- This is similar with FavoritesScreen.

 ## Links	

- https://www.figma.com/file/D2VLqh0xOXbH0zB6cTz053/DroidKaigi_2021_official_App-iOS?node-id=35%3A6718

**Comment by ostk0069** [comment]
I wanna take this ✋

**Comment by ry-itto** [comment]
thanks! assigned 👍 :+1
