### ISSUE TITLE
Use key parameter for `LazyColumn`

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#519]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I would like to improve app performance. 
- 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/4868675fd7d8dee8711ee5a4d1c564c1b86eab97/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedScreen.kt#L308

**Comment by warahiko** [comment]
I want to try this 🤚

**Comment by takahirom** [comment]
Sorry, It has already done in this pr.🙏
If you have any idea of improvement, please do it🙏
https://github.com/DroidKaigi/conference-app-2021/pull/593/files
