### ISSUE TITLE
[iOS] Transition from AboutDroidKaigi Screen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#521]
## Kind (Required)
- Improvement

 ## Overview (Required)

- Please implement following transitions
  - Transition to License page in Setting App.
  - Open `code of conduct` (行動規範) url.
  - Open `privacy policy` (プライバシーポリシー) url.

 ## Links	

-

**Comment by Tech-Nayuta** [comment]
🙌
