### ISSUE TITLE
[iOS] Apply TCA to AboutDroidKaigi screen and SettingScreen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#522]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Title says all.
- Please apply TCA(The composable architecture) to those screens. (Make `**Feature` file and use `Store` in Screens)

 ## Links	

-

**Comment by Tech-Nayuta** [comment]
It is my area of responsibility.
Let me try this issue!🙇‍♂️

**Comment by ry-itto** [comment]
OK! Thanks! Assigned 👍 :+1
