### ISSUE TITLE
[iOS] Toggle language settings from SettingScreen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#524]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please implement toggling language setting from SettingScreen.
- Please edit the current title & summary place with hard code with japanese (ex: `item.title.jaTitle`)

 ## Links	

-

**Comment by yuukiw00w** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks. Assigned 🙏

**Comment by yuukiw00w** [comment]
Is this function "When the switch is turned on, the language setting of the device will be followed, but when it is turned off, the language setting will be Japanese"?
Or is this function "When the switch is turned on, the language setting is Japanese, and when it is turned off, the language setting is English"?
Android doesn't have this feature yet, and it looks like it is implemented to automatically follow the device's language settings.
How should I implement this?

**Comment by yuukiw00w** [comment]
Like Android's dark theme implementation, should I implement three options: "Follow device settings" & "Japanese" & "English"?

**Comment by ry-itto** [comment]
Certainly, it seems that intuitive operation is not possible with the current design.

> Like Android's dark theme implementation, should I implement three options: "Follow device settings" & "Japanese" & "English"?

Can you implement it in the same way as on the Android side? 🙏🏼 
Sorry for the implementation without the design..

**Comment by yuukiw00w** [comment]
Yes, I can.
But it will take some time, I will check this evening or tomorrow.
This feature is not implemented in Android, so I think I need to implement it from Repository(e.g. LanguageRepository) to save the language settings, right?

**Comment by ry-itto** [comment]
yes, you are right.
Pleasb implement kotlin part as well 🙏 :pray
