### ISSUE TITLE
Crash when pause fm player while preparing state

### ISSUE THREAD

**Issue by rmakiyama** [DroidKaigi/conference-app-2021#525]
**Overview (Required)**
- When pause fm player while preparing state, app is crash.

**Steps To Reproduce**

1. Go to 'Podcast'
2. Click on 'play button'
3. Click on 'pause button' right away.

**Expected behavior**
If it's clear, pause fm player.

**Screenshots**
If applicable

**Env:**
 - Device: Pixel 4XL
 - OS: 11
 - branch main

**Additional context**
Any other notes

**Comment by takahirom** [comment]
Good catch!

**Comment by n-seki** [comment]
🙋 
I try debugging!

**Comment by takahirom** [comment]
Thanks! Assigned!
