### ISSUE TITLE
About iOS snapshot in main branch

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#542]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I was wondering if the method of committing a snapshot to the main branch in the repository is not so good because it image will remain as a git object forever. 👀 
- For example, you could create a `golden` branch and write automatic updates to it.
- I think it's okay to leave it as it is, but please tell us what you think. 🙇 

 ## Links	

-

**Comment by ry-itto** [comment]
@takahirom 
> I was wondering if the method of committing a snapshot to the main branch in the repository is not so good because it image will remain as a git object forever. 👀

I think so too. We should solve that problem.
But I think creating `golden` branch way is hard to manage. 😢 

So I guess creating another repository (Managing only snapshots) and reference it from this repository by git-submodules is better.
How about this?

**Comment by mochadwi** [comment]
Does the git submodule will break the CI pipeline? In gitlab, submodule was required to be fetched manually and thus testing (the CI) + maintaining will also cumbersome :(

**Comment by takahirom** [comment]
I don't really understand it, but could it be solved by using Git LFS? 👀 
https://github.com/pointfreeco/swift-snapshot-testing/issues/380#issuecomment-683878791
