### ISSUE TITLE
CI fail with java.io.IOException emulator 21, 23

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#552]
## Kind (Required)

- Improvement

 ## Overview (Required)

```
> Task :uicomponent-compose:main:packageDebugAndroidTest

> Task :uicomponent-compose:feed:connectedDebugAndroidTest

com.android.build.gradle.internal.testing.ConnectedDevice > runTests[test(AVD) - 5.0.2] FAILED 
	java.io.IOException: Unexpected output of command get-current-user, expected a user id found the following output:
	> usage: am [subcommand] [options]
[no message defined]
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Unexpected output of command get-current-user, expected a user id found the following output:
> usage: am [subcommand] [options]
> usage: am start [-D] [-W] [-P <FILE>] [--start-profiler <FILE>]
> [--sampling INTERVAL] [-R COUNT] [-S] [--opengl-trace]
> [--user <USER_ID> | current] <INTENT>
> am startservice [--user <USER_ID> | current] <INTENT>
> am stopservice [--user <USER_ID> | current] <INTENT>
> am force-stop [--user <USER_ID> | all | current] <PACKAGE>
> am kill [--user <USER_ID> | all | current] <PACKAGE>
> am kill-all
> am broadcast [--user <USER_ID> | all | current] <INTENT>
```

 ## Links	

-

**Comment by rsookram** [comment]
I started looking into this issue, and then I found that the min SDK version of this app [is now 24](https://github.com/DroidKaigi/conference-app-2021/commit/ea0396657c896a5931189e05a541cdb05d62c977), so it doesn't really apply anymore. Is the min SDK going to be reduced later, or could this issue be closed now?

What I found so far is that API 21's ActivityManager likely didn't support the `get-current-user` command (note: added [here](https://cs.android.com/android/_/android/platform/frameworks/base/+/0df68cd13b8121aa4e582d8fb59c7589079d6ff9)), and a [different approach](https://android.stackexchange.com/questions/103824/how-to-find-out-currently-running-user-name-id-from-adb/123209#123209) would probably be needed there.

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thank you for your wonderful consideration! 🆒 
Currently, I think MinSdk Version can be 21. 
Because the bug has been fixed. 
https://issuetracker.google.com/issues/194289155#comment23

It may be good to change min sdk with the fix to this issue and add the following fix that you told me. 👍 
https://android.stackexchange.com/questions/103824/how-to-find-out-currently-running-user-name-id-from-adb/123209#123209
