### ISSUE TITLE
Resize small iOS snapshot images

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#562]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - If you use it a little more, it may be used up, so I think it would be better to make the image a little smaller if possible, but is it possible?

![image](https://user-images.githubusercontent.com/1386930/126148281-ba5f2486-85f5-4781-a763-4e1322511584.png)

 ## Links	

-

**Comment by ry-itto** [comment]
@takahirom 
Sorry for late response 🙇🏼 

> it would be better to make the image a little smaller if possible

I think so too. But if make the image smaller, snapshot tests are failed even if I specified lower precision value (0.6).

So I think there are some choices about this.

- Continue with current image size
- Stop to use Git LFS
- Stop to test iOS snapshot testing
  - If above choices are not good, this is okey I think.

**Comment by takahirom** [comment]
@ry-itto 
Thank you for your response 🙏 

> I think so too. But if make the image smaller, snapshot tests are failed even if I specified lower precision value (0.6).

Did you use the `scale` option? 

https://github.com/pointfreeco/swift-snapshot-testing/pull/396/files#diff-3e1681b0623d05afda1993aa39ee2ae8641918d2e1df61acf80b1a367dada06fR14

**Comment by ry-itto** [comment]
@takahirom 
Thank you for your suggestion!
When I tried to use it, it works. (about reducing 75% in my local environment)

So I will make a pull request about it 🙏🏼

**Comment by takahirom** [comment]
Thank you for addressing this issue!

**Comment by takahirom** [comment]
Current 👀 
![image](https://user-images.githubusercontent.com/1386930/128106213-40a6e884-43ca-4a9e-b97c-e14456be6262.png)
