### ISSUE TITLE
DroidKaigi 2021 conference app development schedule

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#606]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- It's basically the same as the #591 issue, but we'll need a little more detail for development.
- We want to create a session list feature by 10/11

## 9/12
- Implement Feed API Fake
- Implement Feed ViewModel Fake

We can create it using the 2019 sessionize response
https://sessionize.com/api/v2/xc8zp3xu/view/all

## 9/19

(Android)

Implement simple text without applying design (If the design can be adapted, I want to adapt it.)

- Session list screen
- Drawer item
- Show DroidKaigi 2021 as the first item

---

- Create an issue for the function required to complete design, and search for contributors on Twitter etc.

## 9/26

(iOS)

Implement simple screens without applying design (If implementation of design is easy, we will implement it.)

- Add timetable in bottom TabBar.
- Remove Message bar in Home tab.
- Timetable screen (can select `day1` , `day2` or `day3` )
- Session detail screen
  - copy link
  - watch this video
    - These should be implemented

## 10/4

- Design completed and fixes for release
- Adapt production API

## 10/11

Release

## 10/18

Release improved version (Android only)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/issues/591

**Comment by ry-itto** [comment]
I'm sorry, we found that I couldn't get enough time until 9/19, so I reschedule on the iOS side. ( change `9/19` to `9/26` )

**Comment by takahirom** [comment]
The Android app also couldn't finish on the 19th. 😅 
I will try to recover tomorrow.
