### ISSUE TITLE
Use navigation scoped ViewModel

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#609]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - Currently, we are using application-scoped ViewModel. But it is not scalable. So we want to migrate to navigation scoped ViewModel
 - Basically, it's easy because you just replace the ViewModel that was provided with Factory.
 - See the pull request below for more information.

https://github.com/DroidKaigi/conference-app-2021/pull/608

Please apply navigation scope ViewModel to these ViewModels

https://github.com/DroidKaigi/conference-app-2021/blob/e59ff96cee2b0f70dc2c09715122652b445b4a3b/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/viewmodel/ProvideRealViewModels.kt#L21-L23

 ## Links	

-

**Comment by tmk815** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
