### ISSUE TITLE
Drawer 2021 item

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#623]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I would like to add an item that can be moved to the timetable.
![image](https://user-images.githubusercontent.com/1386930/133980212-c3b7c251-dfe9-4383-97f9-4cbd4d48c759.png)

 ## Links	

- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=0%3A1

**Comment by tfandkusu** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned!
