### ISSUE TITLE
Favorite feature without view

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#624]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please implement the favorite function to the timetable items.
- There is currently a similar implementation in FeedScreen that can be used as a reference.
- We want to start working on this feature as soon as possible, as it will be the foundation for other features.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/e54d515b6ef2c49b0cd3a5ff3e73ec2a87b0b0b6/data/db/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/UserDataStore.kt#L13

**Comment by t-yusaku** [comment]
🙋

**Comment by takahirom** [comment]
Thanks!! I'm looking forward to your PR🙏
