### ISSUE TITLE
Notify when a favorite session is started

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#625]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This feature is blocked by (favorite feature) https://github.com/DroidKaigi/conference-app-2021/issues/624

- It can be implemented by referring to the SessionAlarm class from last year.
- https://github.com/DroidKaigi/conference-app-2020/blob/4c5533e4611d4bf6007284dd1f61db2fc92eb0ae/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/util/SessionAlarm.kt

 ## Links	

-

**Comment by mune0903** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
@mune0903 Sorry, I'm missed your comment? Are you doing this task?? 👀  🙇 🙇

**Comment by takahirom** [comment]
For now, I assigned you 🙏

**Comment by mune0903** [comment]
Thank you!

**Comment by takahirom** [comment]
@mune0903 
This issue has a milestone date of 10/4. If you have any problems, please let me know! 🙏

**Comment by mune0903** [comment]
@takahirom
I'm sorry I'm late🙇‍♂️
It's still being worked on. So could you please give me more time?
