### ISSUE TITLE
Implementation of filtering of favorites for timetable items

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#626]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It is not in the design, but you can refer to the feed for almost the same functionality.
![image](https://user-images.githubusercontent.com/1386930/133983366-b3c5be59-ec1d-4232-b4ca-fd4c51d387dd.png)
- blocked by #624 

 ## Links	

-

**Comment by t-yusaku** [comment]
If there's no one else, I wanna do this. 🤚

**Comment by takahirom** [comment]
Thanks! Assigned!👍

**Comment by takahirom** [comment]
@t-yusaku 
This issue has a milestone date of 10/4. If you have any problems, please let me know! 🙏

**Comment by t-yusaku** [comment]
@takahirom 
Sorry I'm late 💦
I'm working on this assignment now. Please give me a few more hours 🙇
