### ISSUE TITLE
Timetable Items

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#627]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Use LazyColums to display items in the timetable.
![image](https://user-images.githubusercontent.com/1386930/133984244-41c1c334-4831-4ef0-80e8-fe9c712d7ec4.png)

 ## Links	

-

**Comment by r4wxii** [comment]
I try this issue 🙋‍♀️

**Comment by takahirom** [comment]
Thanks! Assigned 👍 
I'm looking forward to your compose implementation!

**Comment by r4wxii** [comment]
I noticed not working favorites timetable items.
Specifically, Key of `UserDataStore.favorite()` referenced by `TimetableRepositoryImpl` is that of the Feed. I confirmed that it works by changing the key from `KEY_FAVORITES` to `KEY_FAVORITES_TIMETABLE_ITEM_ID`.
Should I fix it after submit Issue/ open PR?

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
How about using `UserDataStore .favoriteTimetableItemIds()` instead of UserDataStore.favorite()?

**Comment by r4wxii** [comment]
I changed the key for confirmation 🙇 
Of course, I was going to fix that way!

**Comment by takahirom** [comment]
You can either separate PR or do them in that PR. 👍

**Comment by takahirom** [comment]
If you have the time, I would suggest creating an issue if you can. But it is not a big issue, so do what you want. 👍

**Comment by r4wxii** [comment]
I will create an issue and then proceed with that PR 🙋

**Comment by takahirom** [comment]
I checked other PR. It seems fixed👀 
https://github.com/DroidKaigi/conference-app-2021/pull/679/files#diff-09835bbfafa08e100a233dd6e2d49174e37b4ecb95b0cae52fa7022a597c4bb1R15

**Comment by r4wxii** [comment]
Sorry, I didn't check it enough 😢 
I'll leave the correction to that 🙏
