### ISSUE TITLE
Timetable item detail screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#629]
## Kind (Required)

- Improvement

 ## Overview (Required)

- The title says everything
- Probably we should use database cache. https://github.com/DroidKaigi/conference-app-2021/issues/628  If you can please implement by FakeViewModel.
![image](https://user-images.githubusercontent.com/1386930/133985341-e3526bf6-aabf-4d53-988f-b9cd7433ca22.png)

 ## Links	

-

**Comment by koji-1009** [comment]
May I challenge this issue?

**Comment by takahirom** [comment]
Sure, Why not? 😄 
I think we probably need to add some categories etc to the TimetableItem, is that okay? 👀

**Comment by koji-1009** [comment]
I checked the JSON.
If there are no major changes after this, I will try to extend TimetableItem to the current JSON form and implement it once.

If it is better to separate the PRs, I will try to deal with them separately. (The first is to update TimetableItem, and the second is to update the UI.)
How should I proceed to make review and deployment easier?

**Comment by takahirom** [comment]
> If there are no major changes after this, I will try to extend TimetableItem to the current JSON form and implement it once.

We don't plan to make any more major changes.

> If it is better to separate the PRs, I will try to deal with them separately. 

I think that's a good idea. 🙏 


> How should I proceed to make review and deployment easier?

The changes to the model will affect the iOS as well, so we need to make them as soon as possible.
I hope to have it done by this weekend(Saturday or Sunday) if possible.

Just a little bit of cognitive alignment, I'd like to make it so that TimetableItem has an instance of the category class, rather than modeling the API as is.
You may want to refer to last year's implementation of the Session class.
If you have any suggestions, please let me know.🙏

少しだけ認識合わせすると、APIをそのままモデル化するのではなく、TimetableItemがcategoryクラスのインスタンスをもっているような形にしたいと思っています。
去年のSessionクラスの実装などを参考にするといいかもしれません。
もし何か意見などがあれば教えて下さい 🙏 

https://github.com/DroidKaigi/conference-app-2020/blob/master/model/src/commonMain/kotlin/io/github/droidkaigi/confsched2020/model/Session.kt

**Comment by koji-1009** [comment]
I'll update the model to PR first. 👍 
(That is the scope of #628. Sorry, I missed it. 🙏 )

I will implement Category based on 2020.
I'll implement it as soon as I can and make it PR, so if it's not what you intended, please comments.

---

※急ぎの話だと思うので日本語で
categoryクラスのインスタンスの持ち方について、了解しました！
SQLDlightの実装になれていないので、意図と違うところがあればPRのコメントでバシバシ指摘いただけますと 🙇

**Comment by koji-1009** [comment]
💪

**Comment by koji-1009** [comment]
Some minor design changes may be required.

### The speaker and the date and time under the title

* The number of characters in the name may different for different people
* The session may have more than one speaker

### Button size for Video and Slide

* If only one side is used, should it be start-aligned?
* If the screen size or text size is enlarged, do we want it to be horizontally scrollable?

---

### Category icon

In the web version, the category icon is displayed, how do I bring this into the app?

It looks like I need to bring the png inside the app or distribute it as a URL. Considering the support for dark mode, it seems like it could be a separate Issue.
(It looks like the 2020 app didn't show this, so it may be new and need to be considered.)

https://droidkaigi.jp/2021/timetable

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
@nontan 

Can you help me with this? 🙏 

```
### The speaker and the date and time under the title

* The number of characters in the name may different for different people
* The session may have more than one speaker
```

![image](https://user-images.githubusercontent.com/1386930/134790197-ebaac18c-6a06-46c8-91a0-fd2a161aeeda.png)

![image](https://user-images.githubusercontent.com/1386930/134790259-f03bf2b1-dbcd-4010-885a-380c26cd53e0.png)

Do you have any suggestions for improvement?
I think we can use FeedScreen Style for the item list in the timetable.

![image](https://user-images.githubusercontent.com/1386930/134790298-0414b106-af1d-4cab-8ba3-703e37dd61a4.png)

In the detail screen of the timetable item, the speaker name is displayed at the bottom of the screen, so you can delete the speaker name text at the top of the screen.

![image](https://user-images.githubusercontent.com/1386930/134790384-991d48d6-c181-4c4e-bbde-200cf76c8e3a.png)

**Comment by takahirom** [comment]
![image](https://user-images.githubusercontent.com/1386930/134790478-365f8408-7bfc-4c16-a8f9-751997a431b9.png)


```
### Button size for Video and Slide

* If only one side is used, should it be start-aligned?
```

I think I'll be fine. 
 @nontan 
What do you think? 🙏 

---

![image](https://user-images.githubusercontent.com/1386930/134790524-b3ceab74-36d6-45fb-ae72-03406a5da65a.png)


```
* If the screen size or text size is enlarged, do we want it to be horizontally scrollable?
```

I think it is good to check and modify after implementation. I may prefer to make the text smaller rather than scrolling. 👀 
@nontan If you have any idea please tell me 🙏

**Comment by takahirom** [comment]
```
Category icon
```

I'll ask the web engineers. 🙏

**Comment by takahirom** [comment]
@nontan 
Let me change the subject. Personally, I feel a little uncomfortable putting "Movie" and "スライド" together.  (Japanese and English together)
How about making "スライド" "SLIDES". 🙏

**Comment by koji-1009** [comment]
> I think it is good to check and modify after implementation.

I Agree! 
It seems like a good idea to try implementing it with a fixed size of 144dp once.

---

Below is an idea.

* The width of the button can be changed according to the display size of the application, such as 360/480/600dp
* If the application has 600dp (or 480dp) or more, set the button size to 144dp; if less, set the size based on 1/2 of the screen size (using autosizing text)

**Comment by takahirom** [comment]
> The width of the button can be changed according to the display size of the application, such as 360/480/600dp
If the application has 600dp (or 480dp) or more, set the button size to 144dp; if less, set the size based on 1/2 of the screen size (using autosizing text)

It looks good 👍 
I have seen such a document, but could not find it. 😭

**Comment by takahirom** [comment]
> category icon

@koji-1009 Can you use this? 🙏 
[session-category.zip](https://github.com/DroidKaigi/conference-app-2021/files/7230786/session-category.zip)

**Comment by koji-1009** [comment]
@takahirom 
Thanks!

**Comment by koji-1009** [comment]
Thank you, @nontan!

Let me proceed first with the name at the top removed and the button fixed at 144dp.
As for the width of the button, I'll try to figure out a way to make it not scroll. (Maybe someone else will have an idea...).
