### ISSUE TITLE
Use Arbor for logging library

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#63]
## Kind (Required)

- Improvement

 ## Overview (Required)

- In this project, println is used as a log in the context of Kotlin Multiplatform.
- It seems that this library can be used on Kotlin Multiplatform like Timber, so I would like to use it.

 ## Links	

- https://github.com/ToxicBakery/Arbor

**Comment by kmachida12345** [comment]
I will try this :raising_hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
