### ISSUE TITLE
Apply toolbar design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#630]
## Kind (Required)

- Improvement

 ## Overview (Required)

- The title says everything
![image](https://user-images.githubusercontent.com/1386930/133987145-8a0b81b9-3b2a-47c1-aaf6-ee856340f37e.png)

 ## Links	

- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=0%3A1

**Comment by chigichan24** [comment]
I wanna try this issue 🙋

**Comment by takahirom** [comment]
Thanks! Assigned!
