### ISSUE TITLE
[iOS] Fix Property names in iOS Staff model with real staff and contributor KMM models

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#636]
## Kind (Required)

- Improvement

 ## Overview (Required)

- This is occurred by https://github.com/DroidKaigi/conference-app-2021/pull/634 changes.
- So, please fix iOS model' s property names with real name.

#### Points need to change (I think this is all)

```
- Change id type to Int
- Change property names
  - name -> username
  - url -> profileUrl
  - image -> iconUrl
```

#### About pull-request

Please create Pull Request to `DroidKaigi2021/use-real-contributor-and-staff-api` branch.

 ## Links	

-

**Comment by 417-72KI** [comment]
👀
