### ISSUE TITLE
[iOS] Run CI for iOS App in Xcode 12.5(.1)

### ISSUE THREAD

**Issue by 417-72KI** [DroidKaigi/conference-app-2021#642]
## Kind (Required)

Choose the suitable template if exists.

- Improvement

 ## Overview (Required)

- `macOS 11 Big Sur` runner has been available on GitHub Actions.
- It means Xcode 12.5 is also available on GitHub Actions!
- My suggestion is to use the latest Xcode on CI.

 ## Links	

- https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/
- https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md

**Comment by ry-itto** [comment]
This is good idea!
Thank you for this issue 🙏🏼 

Recently, in macOS 11 Big Sur runner, Xcode 13.0(13A233) (This is RC version build number) is available as well.
If there is no problem about this, it might be good to use this.
