### ISSUE TITLE
Use compose material icons instead of VectorDrawable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#646]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I think we can use it's icons 😄 
- https://developer.android.com/reference/kotlin/androidx/compose/material/icons/package-summary?hl=ja
- https://github.com/DroidKaigi/conference-app-2021/tree/main/uicomponent-compose/main/src/main/res/drawable

 ## Links	

-

**Comment by kuramu1108** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
