### ISSUE TITLE
[iOS] Apply Staff and Contributor API response to AboutScreen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#649]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, there are no data in iOS AboutScreen and no API calls in there.
- So please call API via Staff/Contributor Repository.
  - call them from `AboutFeature` not `AppFeature` .

 ## Links	

-

**Comment by HironobuIga** [comment]
I'd like to try this issue :)

**Comment by ry-itto** [comment]
Thanks! Assigned 👍
@HironobuIga @

**Comment by HironobuIga** [comment]
Thank you! 👍

**Comment by HironobuIga** [comment]
@ry-itto 
I tried this issue, but I couldn't implement in my spare time...
I'd like to give up, very sorry .... 🙏

**Comment by ry-itto** [comment]
@HironobuIga 
It's okey!
Thank you for trying this issue!
