### ISSUE TITLE
Move compose dependencies to Dep.kt

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#65]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There are some parts that specify direct compose dependencies, so I want to put them together in Dep.kt.

 ## Links	

-  https://github.com/DroidKaigi/conference-app-2021/blob/d45ad777f4b29efa9867052df80e2b50dcabeeaa/uicomponent-compose/main/build.gradle#L70-L78
- https://github.com/DroidKaigi/conference-app-2021/blob/be4293122b884513b9aa02f088965a85832742e5/buildSrc/src/main/java/Dep.kt#L4-L6

**Comment by YuheiKawakami** [comment]
I'll try it 🙋‍♂️

**Comment by takahirom** [comment]
Thank you! Assigned 👍
