### ISSUE TITLE
Move AndroidX dependencies to Dep.kt

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#68]
## Kind (Required)

- Improvement

 ## Overview (Required)

- There are some parts that specify direct compose dependencies, so I want to put them together in Dep.kt.
- However, do not replace the compose dependency as it will be done in #65 .

 ## Links	

-

**Comment by Index197511** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks!Assigned!
