### ISSUE TITLE
[iOS] Error handling in AboutScreen

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2021#684]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, no error handling and error page in AboutScreen. So please implement error page in AboutScreen.
  - Please implement with `SwitchStore` same as TimetableFeature

 ## Links	

-

**Comment by HironobuIga** [comment]
Could I do this ? I tried before and I think I can do.

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by HironobuIga** [comment]
I recreated PR because there are many conflicts. I appreciate if you check new PR.
Sorry for inconvenience.
