### ISSUE TITLE
Fix wrong date tab name

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#686]
## Kind (Required)

- Improvement

 ## Overview (Required)
![image](https://user-images.githubusercontent.com/1386930/135051991-808d92d5-504d-45f1-b0f8-ddeab7e02442.png)

 ## Links	

-

**Comment by kmachida12345** [comment]
:raising_hand_man:

**Comment by takahirom** [comment]
Thanks! Assigned!
