### ISSUE TITLE
Make the API module work on iOS

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#69]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, adding an iOS target in the Kotlin Multiplatform settings will prevent code completion on the IDE. Probably a problem with GitLiveApp/firebase-kotlin-sdk.
- I want to solve this problem and enable iOS targeting.

 ## Links	

-

**Comment by watanavex** [comment]
Probably, adding it to `gradle.properties` will solve it.

```
kotlin.mpp.enableGranularSourceSetsMetadata=true
kotlin.native.enableDependencyPropagation=false
```

https://kotlinlang.org/docs/migrating-multiplatform-project-to-14.html#try-the-hierarchical-project-structure
https://kotlinlang.org/docs/mpp-share-on-platforms.html#share-code-on-similar-platforms

**Comment by watanavex** [comment]
It's working fine in my environment 👍 
If this is correct, I will create a pull-request 🙌

**Comment by takahirom** [comment]
Thank you for investigating! Assigned!!

**Comment by myihsan** [comment]
The problem seems like `commonMain` is using [Arbor](https://github.com/ToxicBakery/Arbor) which does not support iOS.

**Comment by takahirom** [comment]
I removed the arbor library. Thank you for reporting!
