### ISSUE TITLE
Auto link for timetable detail tag line.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#693]
## Kind (Required)

- Improvement

 ## Overview (Required)

Auto link for tag line
![image](https://user-images.githubusercontent.com/1386930/135245952-5a88ed21-4207-42f1-af90-0f0aae0c8d96.png)

 ## Links	

-

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by nkzsdy** [comment]
I have a question.

Looking at the values of TimetableSpeaker, I think it's not the tagLine that should be linked, but the bio.
I'm going to link the bio, is that OK?
````
ex)

TimetableSpeaker(name=Yuki Anzai, iconUrl=https://sessionize.com/image/74af-400o400o2-01-aece-4bf4-b755-32fda033b3bd.b27ac996-bd96-4 dcd-8be0-9acd46b4e835.png, bio=Yuki Anzai
- twitter : https://twitter.com/yanzm
- blog : http://y-anz-m.blogspot.jp/ (Y.A.M's miscellaneous journal)
- Ufica Inc.
- book : Master of Fragment and others
, tagLine=Ufica Inc.)
```
