### ISSUE TITLE
Can we implement robot item? 🤖 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#70]
## Kind (Required)

- Improvement

 ## Overview (Required)

When the size of the article list is larger than the size of the screen, robot is displayed as the last item.

![image](https://user-images.githubusercontent.com/1386930/108617628-5ad9c800-745b-11eb-9bda-987ea66312a5.png)

 ## Links	

-

**Comment by felix925** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 🤖
