### ISSUE TITLE
The title and content of the tab do not match

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#71]
## Kind (Required)

- Improvement

 ## Overview (Required)

- The mapping is reversed, please correct it.
![image](https://user-images.githubusercontent.com/1386930/108617906-2bc45600-745d-11eb-9864-0a04e88311f3.png)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/f6d311de4fb522d412f5786022474305b7048ac0/data/api/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/KtorFeedApi.kt#L42-L65

**Comment by gibachan** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! We're looking forward to your PR!
