### ISSUE TITLE
Language settings do not work.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#714]
## Kind (Required)
- Bug report (please use the other template)

 ## Overview (Required)

-  We can't save the Language settings in the DroidKaigi Android app
- 

 ## Links	

![check](https://user-images.githubusercontent.com/1386930/135737919-c2506266-0a47-487a-9b25-eef75dbb10ad.gif)
-

**Comment by myoshita** [comment]
🙋‍♂️
