### ISSUE TITLE
Stop centering when filtering in timetable screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#716]
## Kind (Required)

- Improvement

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/135737953-0c5bfa06-ed0c-4ab7-befa-874611b6dab7.png)

 ## Links	

-

**Comment by HironobuIga** [comment]
🙋🏻‍♂️

**Comment by takahirom** [comment]
Assigned!!
