### ISSUE TITLE
Use app icon from 2020 app

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#73]
## Kind (Required)

- Improvement

 ## Overview (Required)

- It may change, but at first, I am considering copying the 2020 icon and using it.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020/tree/master/android-base/src/main/res

**Comment by marshi** [comment]
I'll try it 🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned 🙏
