### ISSUE TITLE
Add icon to README

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#74]
Blocked by #73

## Kind (Required)

- Improvement

 ## Overview (Required)

- It looks like a README for the 2020 app.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2020

**Comment by HiroyukiYagihashi** [comment]
I would like to work on this issue.

**Comment by tomoya0x00** [comment]
Thanks! Assigned ❤️
