### ISSUE TITLE
Change the name of DroidKaigi2021ArticleItem to PickupArticleItem and delete  DroidKaigi2021ArticleItem logic

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#751]
## Kind (Required)

- Improvement

 ## Overview (Required)

- DroidKaigi2021 has ended. Therefore, the logic in DroidKaigi2021ArticleItem is no longer needed. 🗑️ 
- isDroidKaigiEnd value:  https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedScreen.kt#L335
- And I want to change the name of DroidKaigi2021ArticleItem to PickupArticleItem 📛 
- https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/DroidKaigi2021ArticleItem.kt#L33

 ## Links	

-

**Comment by aqua-ix** [comment]
I'd like to try this issue.
