### ISSUE TITLE
Make the DB module work on iOS

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#76]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Add an iOS target and try the KeychainSettings or AppleSettings implementation of russhwolf/multiplatform-settings.

 ## Links	

- https://github.com/russhwolf/multiplatform-settings#apple-keychain

**Comment by watanavex** [comment]
I wanna try it 🙌

**Comment by mhidaka** [comment]
Thank you! please go ahead!
