### ISSUE TITLE
Transit to chrome custom tab using navigation component

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#77]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Currently, I'm doing something with context, but it doesn't seem to be a good way.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/610ad01d00a673211e9bcef716762c367cdb53d6/uicomponent-compose/main/src/main/java/io/github/droidkaigi/feeder/AppContent.kt#L59-L65

**Comment by fornewid** [comment]
:raising_hand_man:

**Comment by takahirom** [comment]
Thank you for always tackling difficult problems! Assigned 👍
