### ISSUE TITLE
Transition animation when switching tab content

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#79]
## Kind (Required)

- Improvement

 ## Overview (Required)
- According to Material Design's motion system, this app should use Fade through in such cases.

 ## Links	

- https://material.io/design/motion/the-motion-system.html#fade-through

**Comment by fornewid** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thank you! Maybe it's blocked below. Please tell me that you can always give up if it is difficult.
https://issuetracker.google.com/issues/172112072
