### ISSUE TITLE
Fix drawer navigation of settings

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#83]
**Overview (Required)**
- When you select settings from the navigation drawer, it will transition to about this app without transitioning to settings.

**Steps To Reproduce**

1. Go to 'Navigation Drawer'
2. Click on 'Settings'
4. About tab is selected

**Expected behavior**
Show settings tab

**Screenshots**

https://user-images.githubusercontent.com/1386930/108644691-74c6e980-74f3-11eb-8eca-94e09e2cea2c.mp4

**Additional context**
Probably we can fix it by changing "about_this_app"
https://github.com/DroidKaigi/conference-app-2021/blob/610ad01d00a673211e9bcef716762c367cdb53d6/uicomponent-compose/other/src/main/java/io/github/droidkaigi/feeder/other/OtherScreen.kt#L46

**Comment by Pluu** [comment]
🙋‍♂️

Is it okay to set the routepath key to `setting`?

**Comment by takahirom** [comment]
OK!
Thanks! Assigned!
