### ISSUE TITLE
Prevent backdrop from moving up and down on other screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#85]
## Kind (Required)

- Improvement

 ## Overview (Required)

https://user-images.githubusercontent.com/1386930/108645294-bce70b80-74f5-11eb-81ea-ff6683fb600a.mp4

- On other screens, I don't want to move the backdrop because there is no content even if I lower the backdrop down. Now it goes up and down 1dp.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2021/blob/main/uicomponent-compose/other/src/main/java/io/github/droidkaigi/feeder/other/OtherScreen.kt#L89

**Comment by ue-moo** [comment]
🙋‍♂️

**Comment by ue-moo** [comment]
@takahirom 
Thanks for approval! → #189 
Plz assign me with this issue 🙇

**Comment by yurihondo** [comment]
@ue-moo 
Ooops..Sorry.
I've just assign you with this issue, please check 🙇

**Comment by ue-moo** [comment]
@yurihondo 
Thank you for you help :)
