### ISSUE TITLE
Change app name to DroidKaigi 2021

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#86]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Now the name is conference-app-2020, but the correct name is DroidKaigi 2021.

 ## Links	

-

**Comment by Dai1678** [comment]
@takahirom 
I will try this issue!

**Comment by takahirom** [comment]
Thank you for fast taking issue!!🚀 Assigned!
