### ISSUE TITLE
Animate the frame to move when a tab is selected

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#87]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Perhaps this is very difficult, but can you animate this corner cut frame to move?

![image](https://user-images.githubusercontent.com/1386930/108819312-0c186380-75fe-11eb-976d-b97f2f00b232.png)

 ## Links	

-

**Comment by ntsk** [comment]
:raising_hand_man:

I don't know if it can be done, but I will try it with reference to [JetSnack](https://github.com/android/compose-samples/tree/main/Jetsnack).

<img src=https://user-images.githubusercontent.com/5681281/109499756-a97d0700-7ad8-11eb-9dbe-c82979bcff95.gif width=300>

**Comment by takahirom** [comment]
🆒 
Please try it 🙏 If it's difficult, you can always give up.
