### ISSUE TITLE
Prototype image scale type

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#88]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Designers seem to be worried about image proportions.
I think the feed image of this app is center crop now, but I would like to try patterns such as center inside, take screenshots, ask the designer for a good pattern, and implement it.

 ## Links	

-
![image](https://user-images.githubusercontent.com/1386930/108820680-e55b2c80-75ff-11eb-88bd-b46751fe382c.png)

**Comment by maho-ya** [comment]
Hello, I would like to work on this issue.

**Comment by takahirom** [comment]
Thank you! Assigned :+1:

**Comment by maho-ya** [comment]
Thank you. I will do it.

**Comment by maho-ya** [comment]
@takahirom 
Hi, I have a question.
I noticed that the layout of the feed images changed during testing, is this the correct design?
It looks like the image has a border as shown below.

Figma design | App (9fe747b)
:--: | :--:
<img width="143" alt="スクリーンショット 2021-03-02 21 12 36" src="https://user-images.githubusercontent.com/32348624/109647448-a5b2b880-7b9c-11eb-9080-8f4290dff628.png"> | <img width="143" alt="figma" src="https://user-images.githubusercontent.com/32348624/109646833-ecec7980-7b9b-11eb-97fa-b1b488412346.png">

Figma design does not seem to have a border on it.

It looks like the change was made in the next commit.
https://github.com/DroidKaigi/conference-app-2021/pull/216/commits/1559dfa4b258e3dca2544db8503d8409f62ac881#diff-0f147b1df64e1c36bd083a668d0e7fadbfd8443373a08515fc235b2c85896877R85

I couldn't find anything about adding borders to the related issue(#115) as well.

**Comment by takahirom** [comment]
Thank you for noticing! It is a bug. Can you remove and try it?
The point that the designer cares about is how it looks when a 16: 9 image is included.
