### ISSUE TITLE
Change heart position

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#89]
## Kind (Required)

- Improvement

 ## Overview (Required)

-  Apparently, the position of the heart should be aligned with the bottom of the image.
![image](https://user-images.githubusercontent.com/1386930/108823156-6667f300-7603-11eb-9e30-8d2e4aa86fe1.png)

![image](https://user-images.githubusercontent.com/1386930/108823331-9e6f3600-7603-11eb-9414-3a747a7b77ec.png)

 ## Links	

-

**Comment by souta0104** [comment]
🖐

**Comment by takahirom** [comment]
Thanks! Assigned!
