### ISSUE TITLE
Change date color and size of feed

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#90]
## Kind (Required)

- Improvement

 ## Overview (Required)

- currently
![image](https://user-images.githubusercontent.com/1386930/108824370-f8243000-7604-11eb-84a4-d1aa642e66a8.png)

- design
![image](https://user-images.githubusercontent.com/1386930/108823958-792ef780-7604-11eb-9818-b6ddf40bf6b7.png)

 ## Links	

-

**Comment by warahiko** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned! 🙇
