### ISSUE TITLE
Try Flipper

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#91]
## Kind (Required)

- Improvement

 ## Overview (Required)

- I've never used it, but I heard it's a good library.
- Probably should we use OkHttp engline?
- https://github.com/DroidKaigi/conference-app-2021/blob/be4293122b884513b9aa02f088965a85832742e5/data/api/src/main/java/io/github/droidkaigi/feeder/data/ApiModule.kt#L25

 ## Links	
- https://fbflipper.com/

**Comment by kafumi** [comment]
Could I try this issue? 🙋‍♂️

**Comment by kafumi** [comment]
Sorry, although this issue is not assigned to me yet, I just created a proposal at #263. I'd appreciate it if it would be okay that I take this issue and you would take a look at the PR.

**Comment by tomoya0x00** [comment]
Sorry, We missed your first comment 🙇 
Anyway, thanks for your PR! We will check it 💪
