### ISSUE TITLE
Layout inspector support for Compose

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#92]
## Kind (Required)

- Improvement

 ## Overview (Required)

 - Probably we can add it support by this.
 - Can you add and check it?

```
// Use the most recent version of Compose available.
debugImplementation "androidx.compose.ui:ui-tooling:1.0.0-alpha11"
debugImplementation "org.jetbrains.kotlin:kotlin-reflect:1.4.21"
```

 ## Links	

- https://developer.android.com/studio/preview/features#compose-layout-inspector

**Comment by sadashi-ota** [comment]
I will try this. 🙋

**Comment by yurihondo** [comment]
@sadashi-ota 
Thank you! Assigned 🙏
