### ISSUE TITLE
Separate Ktor settings from platform-specific and common

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#94]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Right now I'm making it below, but this is code that is only used on Android and should be shared on Multiplatform.

https://github.com/DroidKaigi/conference-app-2021/blob/be4293122b884513b9aa02f088965a85832742e5/data/api/src/main/java/io/github/droidkaigi/feeder/data/ApiModule.kt#L23-L51

- For example, if you can pass platform-specific settings as shown below, you can share logic with Multiplatform.

```kotlin
class MyClient<T : HttpClientEngineConfig>(
    engine: HttpClientEngineFactory<T>,
    configBlock: T.()
    -> Unit,
) {
    private val headerValue = "fuga"
    private val httpClient = HttpClient(engine) {
        defaultRequest {
            header("hoge", headerValue)
        }
        engine(configBlock)
    }
}
```

 ## Links	

-

**Comment by watanavex** [comment]
This is an interesting issue.
I wanna try it 🙌

**Comment by takahirom** [comment]
Thanks as always! Assigned 👍
