### ISSUE TITLE
Improve accecibility

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#98]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Please add a content description for images

 ## Links	

-  https://developer.android.com/jetpack/compose/accessibility

**Comment by mune0903** [comment]
🙋‍♂️
I want to try Accessibility in Compose!

**Comment by takahirom** [comment]
Thanks! If you have any questions, please tell me! 😄
